'use server';

/**
 * @fileOverview A flow for fetching compliance news, generated by an AI prompt.
 *
 * - fetchComplianceNews - A function that returns a list of compliance news items.
 * - ComplianceNewsOutput - The return type for the fetchComplianceNews function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import type { NewsItem } from '@/types/compliance';

// Define the output schema based on the NewsItem type.
const ComplianceNewsOutputSchema = z.array(
  z.object({
    id: z.string().describe("Un identifiant unique pour l'actualité, ex: 'news-1'."),
    title: z.string().describe("Le titre de l'article de presse."),
    date: z.string().describe("La date de publication au format AAAA-MM-JJ."),
    source: z.enum(["CGA", "JORT", "GAFI", "OFAC", "UE", "Autre"]).describe("La source de l'information."),
    description: z.string().describe("Une courte description (1-2 phrases) de l'actualité."),
    url: z.string().optional().describe("L'URL vers l'article complet, si disponible."),
  })
).length(5).describe("Une liste de 5 articles d'actualité sur la conformité.");

export type ComplianceNewsOutput = z.infer<typeof ComplianceNewsOutputSchema>;

// This is the main exported function that the UI will call.
export async function fetchComplianceNews(): Promise<ComplianceNewsOutput> {
  return fetchComplianceNewsFlow();
}

const newsPrompt = ai.definePrompt({
    name: 'newsPrompt',
    input: { schema: z.void() },
    output: { schema: ComplianceNewsOutputSchema },
    prompt: `Tu es un expert en veille réglementaire pour le secteur de l'assurance en Tunisie.
Ta mission est de générer une liste de 5 actualités récentes et pertinentes (fictives mais plausibles) concernant la conformité, la lutte anti-blanchiment (LAB-FT).
Assure-toi que les sources (GAFI, OFAC, UE, CGA, JORT) sont variées et que les dates sont récentes, étalées sur les 2-3 derniers mois.
Le contenu doit être spécifiquement pertinent pour un responsable de la conformité dans une compagnie d'assurance.
Fournis la réponse uniquement dans le format JSON demandé.`,
});

const fetchComplianceNewsFlow = ai.defineFlow(
  {
    name: 'fetchComplianceNewsFlow',
    inputSchema: z.void(),
    outputSchema: ComplianceNewsOutputSchema,
  },
  async () => {
    const { output } = await newsPrompt();
    if (!output) {
      return [];
    }
    // Sort news by date descending to ensure newest is first
    const sortedNews = [...output].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    return sortedNews;
  }
);
