"use client";

import React, { useState, useEffect } from "react";
import {
  Dialog,
  DialogContent,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Pin,
  Sparkles,
  Plus,
  Trash2,
  Users,
  User,
  Layers,
  CheckCircle2,
  Check,
  Loader2,
  Edit3,
  KeyRound,
  RotateCcw,
  Copy,
  Wand2,
} from "lucide-react";
import { ComplianceMemo, MemoPillar, MemoScope, MemoPriority, APP_SECTIONS } from "@/types/memo";
import { useMemos } from "@/contexts/MemoContext";
import { useUser } from "@/contexts/UserContext";
import {
  improveMemoWithAIAction,
  generateAutoTitleAction,
} from "@/app/(app)/memos/actions";
import { extractFaithfulTitle } from "@/lib/memoTitleGenerator";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

interface MemoEditorModalProps {
  isOpen: boolean;
  onClose: () => void;
  memoToEdit: ComplianceMemo | null;
  defaultSectionHref?: string;
  defaultSectionLabel?: string;
}

export const MemoEditorModal: React.FC<MemoEditorModalProps> = ({
  isOpen,
  onClose,
  memoToEdit,
  defaultSectionHref = "/dashboard",
  defaultSectionLabel = "Dashboard Général",
}) => {
  const { addMemo, updateMemo } = useMemos();
  const { user } = useUser();
  const { toast } = useToast();

  const isEditing = Boolean(memoToEdit && memoToEdit.id);

  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [pillar, setPillar] = useState<MemoPillar>("LAB_FT");
  const [scope, setScope] = useState<MemoScope>("COLLABORATIVE");
  const [priority, setPriority] = useState<MemoPriority>("ATTENTION");
  const [associatedSectionHref, setAssociatedSectionHref] = useState(defaultSectionHref);
  const [associatedSectionLabel, setAssociatedSectionLabel] = useState(defaultSectionLabel);
  const [checklistInput, setChecklistInput] = useState("");
  const [checklists, setChecklists] = useState<{ id: string; text: string; completed: boolean }[]>([]);

  // State to allow manual title editing
  const [isManualTitleOpen, setIsManualTitleOpen] = useState(false);

  // Auto-generated Title state
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState("");
  const [isGeneratingTitle, setIsGeneratingTitle] = useState(false);

  // AI Improvement states
  const [isImproving, setIsImproving] = useState(false);
  const [improvedSuccess, setImprovedSuccess] = useState(false);
  const [undoBackup, setUndoBackup] = useState<{
    title: string;
    content: string;
    checklists: { id: string; text: string; completed: boolean }[];
  } | null>(null);

  // Custom API key configuration
  const [customApiKey, setCustomApiKey] = useState("");
  const [showKeyConfig, setShowKeyConfig] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const savedKey = localStorage.getItem("COMPLIANCE_AI_KEY") || "";
      setCustomApiKey(savedKey);
    }
  }, []);

  useEffect(() => {
    if (memoToEdit) {
      setTitle(memoToEdit.title || "");
      setContent(memoToEdit.content || "");
      setPillar(memoToEdit.pillar || "LAB_FT");
      setScope(memoToEdit.scope || "COLLABORATIVE");
      setPriority(memoToEdit.priority || "ATTENTION");
      setAssociatedSectionHref(memoToEdit.associatedSectionHref || defaultSectionHref);
      setAssociatedSectionLabel(memoToEdit.associatedSectionLabel || defaultSectionLabel);
      setChecklists(memoToEdit.checklists || []);
      setIsManualTitleOpen(true);
    } else {
      setTitle("");
      setContent("");
      setPillar("LAB_FT");
      setScope("COLLABORATIVE");
      setPriority("ATTENTION");
      setAssociatedSectionHref(defaultSectionHref);
      setAssociatedSectionLabel(defaultSectionLabel);
      setChecklists([]);
      setIsManualTitleOpen(false);
      setAutoGeneratedTitle("");
    }
    setImprovedSuccess(false);
    setUndoBackup(null);
  }, [memoToEdit, defaultSectionHref, defaultSectionLabel, isOpen]);

  // Debounced intelligent AI title synthesizer triggered while typing
  useEffect(() => {
    if (!content.trim()) {
      setAutoGeneratedTitle("");
      setIsGeneratingTitle(false);
      return;
    }

    // Instant local semantic extraction first
    const immediateTitle = extractFaithfulTitle(content, pillar, associatedSectionLabel);
    setAutoGeneratedTitle(immediateTitle);

    // If string is long enough, trigger async AI synthesizer with debounce
    if (content.trim().length > 15 && !title) {
      setIsGeneratingTitle(true);
      const timer = setTimeout(async () => {
        try {
          const res = await generateAutoTitleAction({
            content: content.trim(),
            pillar,
            sectionLabel: associatedSectionLabel,
          });
          if (res && res.title && res.title.trim()) {
            setAutoGeneratedTitle(res.title.trim());
          }
        } catch (e) {
          console.warn("Async title generator error:", e);
        } finally {
          setIsGeneratingTitle(false);
        }
      }, 500);

      return () => clearTimeout(timer);
    }
  }, [content, pillar, associatedSectionLabel, title]);

  const handleAddChecklistItem = () => {
    if (!checklistInput.trim()) return;
    setChecklists((prev) => [
      ...prev,
      {
        id: `chk-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
        text: checklistInput.trim(),
        completed: false,
      },
    ]);
    setChecklistInput("");
  };

  const handleRemoveChecklistItem = (id: string) => {
    setChecklists((prev) => prev.filter((item) => item.id !== id));
  };

  const handleSectionChange = (href: string) => {
    const selected = APP_SECTIONS.find((s) => s.href === href);
    setAssociatedSectionHref(href);
    setAssociatedSectionLabel(selected ? selected.label : "Section personnalisée");
  };

  const handleSaveApiKey = (key: string) => {
    setCustomApiKey(key);
    if (typeof window !== "undefined") {
      localStorage.setItem("COMPLIANCE_AI_KEY", key.trim());
    }
    toast({
      title: "Clé API enregistrée",
      description: "Votre clé a été sauvegardée localement dans votre navigateur.",
    });
    setShowKeyConfig(false);
  };

  // ─── AMÉLIORATION SIMPLE DIRECTE VIA IA ────────────────────────────────────
  const handleImproveWithAI = async () => {
    if (!content.trim()) {
      toast({
        title: "Notes requises",
        description: "Veuillez d'abord rédiger vos notes ou vos points bruts dans le mémo.",
        variant: "destructive",
      });
      return;
    }

    setIsImproving(true);
    setUndoBackup({
      title: title || autoGeneratedTitle,
      content,
      checklists: [...checklists],
    });

    try {
      const result = await improveMemoWithAIAction({
        rawText: content,
        pillar,
        sectionLabel: associatedSectionLabel,
        customApiKey: customApiKey.trim() || undefined,
      });

      if (result.error) {
        toast({
          title: "Erreur IA",
          description: result.error,
          variant: "destructive",
        });
        return;
      }

      // 1. Le titre devient le résumé synthétique du sujet
      if (result.summaryTitle) {
        setTitle(result.summaryTitle);
        setAutoGeneratedTitle(result.summaryTitle);
        setIsManualTitleOpen(true);
      }

      // 2. Le texte est formulé de façon pro et organisée avec des points
      if (result.organizedText) {
        setContent(result.organizedText);
      }

      // 3. Extraction d'actions dans la checklist si disponibles
      if (result.suggestedChecklist && result.suggestedChecklist.length > 0) {
        const newItems = result.suggestedChecklist.map((item) => ({
          id: `chk-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
          text: item,
          completed: false,
        }));
        setChecklists((prev) => [...prev, ...newItems]);
      }

      setImprovedSuccess(true);
      toast({
        title: "Mémo professionnalisé ✨",
        description: "Le texte a été organisé avec des points clairs et le titre résume le sujet.",
      });
    } catch (err) {
      console.error(err);
      toast({
        title: "Erreur IA",
        description: "Impossible d'améliorer le mémo pour le moment.",
        variant: "destructive",
      });
    } finally {
      setIsImproving(false);
    }
  };

  const handleRestoreOriginalNotes = () => {
    if (!undoBackup) return;
    setTitle(undoBackup.title);
    setAutoGeneratedTitle(undoBackup.title);
    setContent(undoBackup.content);
    setChecklists(undoBackup.checklists);
    setImprovedSuccess(false);
    setUndoBackup(null);
    toast({
      title: "Notes rétablies",
      description: "Votre texte et votre titre initiaux ont été restaurés.",
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!content.trim()) {
      toast({
        title: "Contenu requis",
        description: "Veuillez rédiger le contenu de votre mémo.",
        variant: "destructive",
      });
      return;
    }

    const finalTitle = (title.trim() || autoGeneratedTitle.trim() || extractFaithfulTitle(content, pillar, associatedSectionLabel));

    if (isEditing && memoToEdit) {
      await updateMemo(memoToEdit.id, {
        title: finalTitle,
        content: content.trim(),
        pillar,
        scope,
        priority,
        associatedSectionHref,
        associatedSectionLabel,
        checklists,
      });
      toast({
        title: "Mémo mis à jour",
        description: `Le mémo "${finalTitle}" a été modifié avec succès.`,
      });
    } else {
      await addMemo({
        title: finalTitle,
        content: content.trim(),
        pillar,
        scope,
        priority,
        associatedSectionHref,
        associatedSectionLabel,
        checklists,
        authorId: user?.id || "user-1",
        authorName: user?.name || "Collaborateur",
        authorRole: user?.role || "Compliance Officer",
      });
      toast({
        title: "Mémo créé",
        description: `Le mémo "${finalTitle}" a été épinglé avec succès.`,
      });
    }

    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-xl md:max-w-2xl max-h-[92vh] overflow-y-auto p-0 border-0 rounded-3xl shadow-2xl bg-amber-50/95 dark:bg-slate-900 border-amber-200/80 dark:border-slate-800">
        {/* Style Post-it authentique avec punaise */}
        <div className="relative p-6 space-y-4">
          {/* Ruban / Pin en haut au centre */}
          <div className="absolute -top-3 left-1/2 transform -translate-x-1/2 flex items-center justify-center">
            <div className="h-7 w-7 rounded-full bg-rose-500 shadow-md border-2 border-white flex items-center justify-center text-white">
              <Pin className="h-4 w-4 fill-current rotate-45" />
            </div>
          </div>

          {/* En-tête du Post-it */}
          <div className="flex justify-between items-center pb-3 border-b border-amber-200/60 dark:border-slate-800 pt-1">
            <div className="flex items-center gap-2">
              <span className="text-base font-black uppercase tracking-tight flex items-center gap-1.5 text-slate-900 dark:text-white">
                <Pin className="h-4 w-4 fill-current text-rose-500 rotate-12" />
                {isEditing ? "Modifier le Post-it" : "Nouveau Mémo Post-it"}
              </span>
            </div>

            <div className="flex items-center gap-2 mr-6">
              <button
                type="button"
                onClick={() => setShowKeyConfig(!showKeyConfig)}
                className="p-1.5 rounded-lg text-slate-400 hover:text-amber-600 dark:hover:text-amber-400 text-xs border border-amber-200/40 dark:border-slate-800 bg-white/60 dark:bg-slate-800/60 transition-colors"
                title="Configuration clé API IA (Optionnelle)"
              >
                <KeyRound className="h-3.5 w-3.5" />
              </button>
              <Badge variant="outline" className="text-[9px] font-black uppercase tracking-wider bg-amber-500/10 text-amber-700 dark:text-amber-300 border-amber-300/60 dark:border-amber-700/60">
                📌 Note Active
              </Badge>
            </div>
          </div>

          {/* Configuration Clé API Optionnelle (dépliable) */}
          {showKeyConfig && (
            <div className="p-3 bg-white/90 dark:bg-slate-800/90 rounded-2xl border border-amber-300/70 dark:border-slate-700 space-y-2 animate-in fade-in duration-200 text-xs shadow-sm">
              <div className="flex justify-between items-center">
                <span className="font-bold text-slate-800 dark:text-slate-200 flex items-center gap-1.5">
                  <KeyRound className="h-3.5 w-3.5 text-amber-500" /> Clé API IA Personnelle (Groq, Gemini, OpenAI)
                </span>
                <button
                  type="button"
                  onClick={() => setShowKeyConfig(false)}
                  className="text-slate-400 hover:text-slate-600"
                >
                  ✕
                </button>
              </div>
              <p className="text-[11px] text-slate-500 dark:text-slate-400">
                Optionnel : Vous pouvez renseigner votre clé personnelle Groq (<code className="font-mono text-indigo-600">gsk_...</code>), Gemini (<code className="font-mono text-indigo-600">AIza...</code>) ou OpenAI (<code className="font-mono text-indigo-600">sk-...</code>). Sans clé, le moteur autonome GRC assure 100% du service.
              </p>
              <div className="flex gap-2">
                <Input
                  value={customApiKey}
                  onChange={(e) => setCustomApiKey(e.target.value)}
                  placeholder="Ex: gsk_... ou AIza... ou sk-..."
                  className="text-xs h-8 rounded-xl font-mono"
                />
                <Button
                  type="button"
                  size="sm"
                  onClick={() => handleSaveApiKey(customApiKey)}
                  className="h-8 px-3 rounded-xl bg-amber-500 hover:bg-amber-600 text-white text-xs font-bold shrink-0"
                >
                  Enregistrer
                </Button>
              </div>
            </div>
          )}

          <form onSubmit={handleSubmit} className="space-y-4 pt-1">
            {/* Champ Titre du Mémo (Résumé synthétique du sujet) */}
            {(!isManualTitleOpen && !isEditing) ? (
              <div className="p-3 rounded-2xl bg-amber-500/10 dark:bg-slate-800/80 border border-amber-300/60 dark:border-amber-700/50 flex items-center justify-between gap-3 shadow-xs">
                <div className="flex items-center gap-2.5 min-w-0 flex-1">
                  <div className="p-1.5 rounded-xl bg-amber-500 text-white shrink-0 shadow-sm">
                    {isGeneratingTitle ? (
                      <Loader2 className="h-3.5 w-3.5 animate-spin text-white" />
                    ) : (
                      <Sparkles className="h-3.5 w-3.5" />
                    )}
                  </div>
                  <div className="min-w-0 flex-1">
                    <span className="text-[9.5px] font-black uppercase text-amber-800 dark:text-amber-300 tracking-wider block">
                      Titre du Mémo (Résumé du sujet)
                    </span>
                    <p className="text-xs font-black text-slate-900 dark:text-white truncate">
                      {content.trim()
                        ? (title || autoGeneratedTitle || "Génération du titre en cours...")
                        : "Rédigez vos notes pour résumer automatiquement le sujet..."}
                    </p>
                  </div>
                </div>

                {content.trim() && (
                  <button
                    type="button"
                    onClick={() => {
                      setTitle(title || autoGeneratedTitle);
                      setIsManualTitleOpen(true);
                    }}
                    className="p-1.5 rounded-lg text-amber-700 dark:text-amber-400 hover:bg-amber-500/20 text-[10px] font-bold shrink-0 flex items-center gap-1 transition-colors"
                    title="Personnaliser le titre manuellement"
                  >
                    <Edit3 className="h-3 w-3" />
                    <span className="hidden sm:inline">Éditer</span>
                  </button>
                )}
              </div>
            ) : (
              <div className="space-y-1">
                <div className="flex justify-between items-center">
                  <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                    Titre du Mémo (Résumé du sujet)
                  </label>
                  <button
                    type="button"
                    onClick={() => {
                      const faithful = extractFaithfulTitle(content, pillar, associatedSectionLabel);
                      setTitle(faithful);
                    }}
                    className="text-[9.5px] font-bold text-amber-700 dark:text-amber-400 hover:underline flex items-center gap-1"
                    title="Régénérer le titre résumé du sujet"
                  >
                    <Wand2 className="h-2.5 w-2.5" /> Régénérer résumé
                  </button>
                </div>
                <Input
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="Titre résumé du sujet..."
                  className="text-sm font-black tracking-tight rounded-xl bg-white/90 dark:bg-slate-800/90 border-amber-200 dark:border-slate-700 text-slate-900 dark:text-white shadow-xs focus-visible:ring-1 focus-visible:ring-amber-500"
                />
              </div>
            )}

            {/* Badges / Sélecteurs Métier, Portée & Priorité */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
              {/* Volet */}
              <div className="space-y-1">
                <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                  Volet Métier
                </label>
                <select
                  value={pillar}
                  onChange={(e) => setPillar(e.target.value as MemoPillar)}
                  className="w-full text-xs font-bold rounded-xl p-2 bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 outline-none shadow-xs"
                >
                  <option value="LAB_FT">🛡️ LAB / FT</option>
                  <option value="CONFORMITE_REGLEMENTAIRE">⚖️ Conformité Réglementaire</option>
                  <option value="GENERAL">📌 Général</option>
                </select>
              </div>

              {/* Portée */}
              <div className="space-y-1">
                <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                  Portée / Visibilité
                </label>
                <div className="grid grid-cols-2 gap-1 p-1 rounded-xl bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 shadow-xs">
                  <button
                    type="button"
                    onClick={() => setScope("COLLABORATIVE")}
                    className={cn(
                      "py-1 px-1.5 text-[10px] font-bold rounded-lg transition-all flex items-center justify-center gap-1",
                      scope === "COLLABORATIVE"
                        ? "bg-indigo-600 text-white shadow-sm"
                        : "text-slate-500 hover:text-slate-900 dark:hover:text-white"
                    )}
                  >
                    <Users className="h-3 w-3" />
                    Équipe
                  </button>
                  <button
                    type="button"
                    onClick={() => setScope("PRIVATE")}
                    className={cn(
                      "py-1 px-1.5 text-[10px] font-bold rounded-lg transition-all flex items-center justify-center gap-1",
                      scope === "PRIVATE"
                        ? "bg-slate-800 dark:bg-slate-700 text-white shadow-sm"
                        : "text-slate-500 hover:text-slate-900 dark:hover:text-white"
                    )}
                  >
                    <User className="h-3 w-3" />
                    Privé
                  </button>
                </div>
              </div>

              {/* Priorité */}
              <div className="space-y-1">
                <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                  Niveau de Priorité
                </label>
                <select
                  value={priority}
                  onChange={(e) => setPriority(e.target.value as MemoPriority)}
                  className="w-full text-xs font-bold rounded-xl p-2 bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 outline-none shadow-xs"
                >
                  <option value="URGENT">🚨 Urgent / Bloquant</option>
                  <option value="ATTENTION">⚡ Attention</option>
                  <option value="INFO">🟢 Information</option>
                </select>
              </div>
            </div>

            {/* Section Applicative Associée */}
            <div className="space-y-1">
              <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider flex items-center gap-1">
                <Layers className="h-3 w-3 text-indigo-500" />
                Section Applicative Associée
              </label>
              <select
                value={associatedSectionHref}
                onChange={(e) => handleSectionChange(e.target.value)}
                className="w-full text-xs font-semibold rounded-xl p-2 bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 outline-none shadow-xs truncate"
              >
                {APP_SECTIONS.map((sec) => (
                  <option key={sec.href} value={sec.href}>
                    [{sec.group}] — {sec.label}
                  </option>
                ))}
              </select>
            </div>

            {/* Zone de texte & Bouton Amélioration IA Simple */}
            <div className="space-y-2">
              <div className="flex justify-between items-center flex-wrap gap-2">
                <label className="text-xs sm:text-sm font-black text-slate-800 dark:text-slate-200 uppercase tracking-wider">
                  Contenu du mémo <span className="text-rose-500">*</span>
                </label>

                {/* 🌟 LE BOUTON D'AMÉLIORATION IA UNIQUE, SIMPLE & EFFICACE */}
                <Button
                  type="button"
                  disabled={isImproving || !content.trim()}
                  onClick={handleImproveWithAI}
                  className="h-8 px-3.5 rounded-xl bg-gradient-to-r from-amber-500 via-amber-600 to-indigo-600 hover:from-amber-600 hover:to-indigo-700 text-white text-xs font-black gap-1.5 shadow-md shadow-amber-500/20 transition-all disabled:opacity-40"
                  title="Améliore vos notes brutes : organise le texte avec des points clairs et résume le sujet dans le titre"
                >
                  {isImproving ? (
                    <>
                      <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      <span>Organisation en cours...</span>
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-3.5 w-3.5 text-amber-200 animate-pulse" />
                      <span>Améliorer avec l'IA ✨</span>
                    </>
                  )}
                </Button>
              </div>

              {/* Bannière de confirmation / possibilité de rétablir les notes initiales */}
              {improvedSuccess && undoBackup && (
                <div className="p-2.5 rounded-xl bg-gradient-to-r from-emerald-500/15 via-amber-500/10 to-transparent border border-emerald-300 dark:border-emerald-800 flex items-center justify-between gap-2 text-xs animate-in fade-in duration-200">
                  <span className="font-bold text-emerald-800 dark:text-emerald-300 flex items-center gap-1.5">
                    <Check className="h-3.5 w-3.5 text-emerald-600" />
                    Mémo organisé avec des points clairs & titre résumé du sujet généré !
                  </span>
                  <button
                    type="button"
                    onClick={handleRestoreOriginalNotes}
                    className="text-[11px] font-black text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white flex items-center gap-1 underline transition-colors"
                  >
                    <RotateCcw className="h-3 w-3" /> Rétablir mes notes
                  </button>
                </div>
              )}

              <Textarea
                value={content}
                onChange={(e) => setContent(e.target.value)}
                placeholder="Écrivez vos notes brutes, observations ou points ici... Cliquez ensuite sur 'Améliorer avec l'IA ✨' pour les structurer de façon professionnelle avec des points et générer le titre résumé."
                rows={8}
                className="text-sm sm:text-base rounded-2xl font-medium leading-relaxed bg-white/95 dark:bg-slate-800/95 border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 shadow-xs resize-y focus-visible:ring-1 focus-visible:ring-amber-500 p-3.5"
                required
              />
            </div>

            {/* Checklist / Actions */}
            <div className="space-y-2 pt-1 border-t border-amber-200/60 dark:border-slate-800">
              <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider flex items-center gap-1">
                <CheckCircle2 className="h-3 w-3 text-emerald-500" />
                Checklist / Actions à vérifier
              </label>

              <div className="flex gap-2">
                <Input
                  value={checklistInput}
                  onChange={(e) => setChecklistInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      e.preventDefault();
                      handleAddChecklistItem();
                    }
                  }}
                  placeholder="Ajouter une action (ex: Contrôler la pièce d'identité)..."
                  className="text-xs rounded-xl h-8 bg-white/90 dark:bg-slate-800/90 border-amber-200 dark:border-slate-700"
                />
                <Button
                  type="button"
                  size="sm"
                  onClick={handleAddChecklistItem}
                  className="h-8 px-3 rounded-xl bg-amber-500/20 hover:bg-amber-500/30 text-amber-800 dark:text-amber-200 text-xs font-bold shrink-0"
                >
                  <Plus className="h-3.5 w-3.5 mr-1" />
                  Ajouter
                </Button>
              </div>

              {checklists.length > 0 && (
                <div className="space-y-1 max-h-28 overflow-y-auto pr-1">
                  {checklists.map((chk) => (
                    <div
                      key={chk.id}
                      className="flex items-center justify-between gap-2 px-2.5 py-1.5 bg-white/80 dark:bg-slate-800/80 rounded-xl border border-amber-200/40 dark:border-slate-700 text-xs"
                    >
                      <span className="truncate font-medium text-slate-700 dark:text-slate-300">
                        • {chk.text}
                      </span>
                      <button
                        type="button"
                        onClick={() => handleRemoveChecklistItem(chk.id)}
                        className="text-slate-400 hover:text-rose-500 p-1"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Pied du Post-it */}
            <div className="pt-3 border-t border-amber-200/60 dark:border-slate-800 flex justify-between items-center gap-2">
              <Button
                type="button"
                variant="outline"
                onClick={onClose}
                className="h-9 px-4 rounded-xl text-xs font-semibold bg-white/80 dark:bg-slate-800 border-amber-200 dark:border-slate-700"
              >
                Annuler
              </Button>
              <Button
                type="submit"
                className="h-9 px-5 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-white text-xs font-black shadow-md shadow-amber-500/20"
              >
                {isEditing ? "Enregistrer les modifications" : "Épingler le Post-it 📌"}
              </Button>
            </div>
          </form>

          {/* Effet d'ombre de coin replié en bas à droite */}
          <div
            className="absolute bottom-0 right-0 w-6 h-6 pointer-events-none rounded-br-3xl opacity-30"
            style={{
              background: "linear-gradient(135deg, transparent 50%, rgba(0,0,0,0.15) 50%)",
            }}
          />
        </div>
      </DialogContent>
    </Dialog>
  );
};
