"use client";

import React, { useState, useEffect, useMemo } from "react";
import {
  Dialog,
  DialogContent,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Sparkles,
  Plus,
  Trash2,
  Users,
  User,
  Layers,
  CheckCircle2,
  Check,
  Pin,
  Loader2,
  Wand2,
  Edit3,
  Bot,
  MessageSquare,
  Send,
  Settings2,
  KeyRound,
  ArrowRight,
  Copy,
  RefreshCw,
  ShieldAlert
} from "lucide-react";
import { ComplianceMemo, MemoPillar, MemoScope, MemoPriority, APP_SECTIONS } from "@/types/memo";
import { useMemos } from "@/contexts/MemoContext";
import { useUser } from "@/contexts/UserContext";
import {
  reformulateMemoAction,
  generateAutoTitleAction,
  chatWithMemoAIAction,
  MemoAIStyle,
  ChatWithMemoAIResult,
} from "@/app/(app)/memos/actions";
import { extractFaithfulTitle } from "@/lib/memoTitleGenerator";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

interface MemoEditorModalProps {
  isOpen: boolean;
  onClose: () => void;
  memoToEdit: ComplianceMemo | null;
  defaultSectionHref?: string;
  defaultSectionLabel?: string;
}

export const MemoEditorModal: React.FC<MemoEditorModalProps> = ({
  isOpen,
  onClose,
  memoToEdit,
  defaultSectionHref = "/dashboard",
  defaultSectionLabel = "Dashboard Général",
}) => {
  const { addMemo, updateMemo } = useMemos();
  const { user } = useUser();
  const { toast } = useToast();

  const isEditing = Boolean(memoToEdit && memoToEdit.id);

  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [pillar, setPillar] = useState<MemoPillar>("LAB_FT");
  const [scope, setScope] = useState<MemoScope>("COLLABORATIVE");
  const [priority, setPriority] = useState<MemoPriority>("ATTENTION");
  const [associatedSectionHref, setAssociatedSectionHref] = useState(defaultSectionHref);
  const [associatedSectionLabel, setAssociatedSectionLabel] = useState(defaultSectionLabel);
  const [checklistInput, setChecklistInput] = useState("");
  const [checklists, setChecklists] = useState<{ id: string; text: string; completed: boolean }[]>([]);

  // State to allow manual title override even in creation mode if desired
  const [isManualTitleOpen, setIsManualTitleOpen] = useState(false);

  // Auto-generated Title state
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState("");
  const [isGeneratingTitle, setIsGeneratingTitle] = useState(false);

  // AI Reformulation State
  const [isReformulating, setIsReformulating] = useState(false);
  const [aiStyle, setAiStyle] = useState<MemoAIStyle>("FORMAL");
  const [showAiPreview, setShowAiPreview] = useState(false);
  const [aiSuggestion, setAiSuggestion] = useState<{ title?: string; text?: string; checklist?: string[] } | null>(null);

  // Tab Mode: POSTIT (note classique) vs COPILOT (dialogue & cadrage IA style ChatGPT)
  const [activeTab, setActiveTab] = useState<"POSTIT" | "COPILOT">("POSTIT");

  // AI Copilot Chat State
  const [chatMessages, setChatMessages] = useState<Array<{
    id: string;
    role: "user" | "assistant";
    content: string;
    framingAnalysis?: string;
    suggestedTitle?: string;
    suggestedContent?: string;
    suggestedChecklist?: string[];
    providerUsed?: string;
    timestamp: string;
  }>>([
    {
      id: "welcome-1",
      role: "assistant",
      content:
        "Bonjour ! Je suis votre Copilot IA Conformité (MAE Assurance). Décrivez-moi votre situation, vos constats ou votre problème en langage naturel (comme sur ChatGPT). Je vais cadrer votre besoin, analyser les risques réglementaires (CTAF / CGA) et rédiger un mémo structuré avec checklist.",
      timestamp: new Date().toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" }),
    },
  ]);
  const [chatInput, setChatInput] = useState("");
  const [isChatLoading, setIsChatLoading] = useState(false);
  const [customApiKey, setCustomApiKey] = useState("");
  const [showKeyConfig, setShowKeyConfig] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const savedKey = localStorage.getItem("COMPLIANCE_AI_KEY") || "";
      setCustomApiKey(savedKey);
    }
  }, []);

  useEffect(() => {
    if (memoToEdit) {
      setTitle(memoToEdit.title || "");
      setContent(memoToEdit.content || "");
      setPillar(memoToEdit.pillar || "LAB_FT");
      setScope(memoToEdit.scope || "COLLABORATIVE");
      setPriority(memoToEdit.priority || "ATTENTION");
      setAssociatedSectionHref(memoToEdit.associatedSectionHref || defaultSectionHref);
      setAssociatedSectionLabel(memoToEdit.associatedSectionLabel || defaultSectionLabel);
      setChecklists(memoToEdit.checklists || []);
      setIsManualTitleOpen(true);
    } else {
      setTitle("");
      setContent("");
      setPillar("LAB_FT");
      setScope("COLLABORATIVE");
      setPriority("ATTENTION");
      setAssociatedSectionHref(defaultSectionHref);
      setAssociatedSectionLabel(defaultSectionLabel);
      setChecklists([]);
      setIsManualTitleOpen(false);
      setAutoGeneratedTitle("");
    }
    setShowAiPreview(false);
    setAiSuggestion(null);
  }, [memoToEdit, defaultSectionHref, defaultSectionLabel, isOpen]);

  // Debounced intelligent AI title synthesizer triggered while typing
  useEffect(() => {
    if (!content.trim()) {
      setAutoGeneratedTitle("");
      setIsGeneratingTitle(false);
      return;
    }

    // Instant local semantic extraction first
    const immediateTitle = extractFaithfulTitle(content, pillar, associatedSectionLabel);
    setAutoGeneratedTitle(immediateTitle);

    // If string is long enough, trigger async AI synthesizer with 450ms debounce
    if (content.trim().length > 15) {
      setIsGeneratingTitle(true);
      const timer = setTimeout(async () => {
        try {
          const res = await generateAutoTitleAction({
            content: content.trim(),
            pillar,
            sectionLabel: associatedSectionLabel,
          });
          if (res && res.title && res.title.trim()) {
            setAutoGeneratedTitle(res.title.trim());
          }
        } catch (e) {
          console.warn("Async title generator error:", e);
        } finally {
          setIsGeneratingTitle(false);
        }
      }, 450);

      return () => clearTimeout(timer);
    }
  }, [content, pillar, associatedSectionLabel]);

  const handleAddChecklistItem = () => {
    if (!checklistInput.trim()) return;
    setChecklists((prev) => [
      ...prev,
      {
        id: `chk-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
        text: checklistInput.trim(),
        completed: false,
      },
    ]);
    setChecklistInput("");
  };

  const handleRemoveChecklistItem = (id: string) => {
    setChecklists((prev) => prev.filter((item) => item.id !== id));
  };

  const handleSectionChange = (href: string) => {
    const selected = APP_SECTIONS.find((s) => s.href === href);
    setAssociatedSectionHref(href);
    setAssociatedSectionLabel(selected ? selected.label : "Section personnalisée");
  };

  // AI Reformulation Handler
  const handleReformulate = async (selectedStyle: MemoAIStyle) => {
    if (!content.trim()) {
      toast({
        title: "Texte requis",
        description: "Veuillez d'abord rédiger une ébauche de note pour que l'IA puisse la reformuler.",
        variant: "destructive",
      });
      return;
    }

    setIsReformulating(true);
    setAiStyle(selectedStyle);

    try {
      const result = await reformulateMemoAction({
        text: content,
        title: title || autoGeneratedTitle || undefined,
        pillar,
        style: selectedStyle,
        sectionLabel: associatedSectionLabel,
      });

      if (result.error) {
        toast({
          title: "Erreur IA",
          description: result.error,
          variant: "destructive",
        });
      } else if (result.reformulatedText) {
        setAiSuggestion({
          title: result.suggestedTitle,
          text: result.reformulatedText,
          checklist: result.suggestedChecklist,
        });
        setShowAiPreview(true);
        toast({
          title: "Proposition générée",
          description: `La reformulation IA (${selectedStyle}) est prête.`,
        });
      }
    } catch (err) {
      console.error(err);
      toast({
        title: "Erreur IA",
        description: "Échec de connexion au service d'intelligence cognitive.",
        variant: "destructive",
      });
    } finally {
      setIsReformulating(false);
    }
  };

  const handleApplyAiSuggestion = () => {
    if (!aiSuggestion) return;
    if (aiSuggestion.text) setContent(aiSuggestion.text);
    if (aiSuggestion.title) {
      setTitle(aiSuggestion.title);
      setAutoGeneratedTitle(aiSuggestion.title);
    }
    setShowAiPreview(false);
    toast({
      title: "Post-it mis à jour !",
      description: "Le texte reformulé a été inséré dans votre mémo.",
    });
  };

  const handleImportAiChecklist = () => {
    if (!aiSuggestion?.checklist || aiSuggestion.checklist.length === 0) return;
    const newItems = aiSuggestion.checklist.map((item) => ({
      id: `chk-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
      text: item,
      completed: false,
    }));
    setChecklists((prev) => [...prev, ...newItems]);
    toast({
      title: "Checklist importée !",
      description: `${newItems.length} point(s) d'action ajouté(s) à la checklist.`,
    });
  };

  const handleSaveApiKey = (key: string) => {
    setCustomApiKey(key);
    if (typeof window !== "undefined") {
      localStorage.setItem("COMPLIANCE_AI_KEY", key.trim());
    }
    toast({
      title: "Clé API enregistrée",
      description: "Votre clé a été sauvegardée localement dans votre navigateur.",
    });
    setShowKeyConfig(false);
  };

  const handleSendChatMessage = async (promptToSend?: string) => {
    const textToSend = (promptToSend || chatInput).trim();
    if (!textToSend) return;

    const userMsgId = `user-${Date.now()}`;
    const newMsg = {
      id: userMsgId,
      role: "user" as const,
      content: textToSend,
      timestamp: new Date().toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" }),
    };

    setChatMessages((prev) => [...prev, newMsg]);
    if (!promptToSend) setChatInput("");
    setIsChatLoading(true);

    try {
      const historyPayload = chatMessages
        .filter((m) => m.id !== "welcome-1")
        .map((m) => ({ role: m.role, content: m.content }));

      const result = await chatWithMemoAIAction({
        userPrompt: textToSend,
        history: historyPayload,
        currentMemoText: content,
        currentMemoTitle: title || autoGeneratedTitle,
        pillar,
        sectionLabel: associatedSectionLabel,
        customApiKey: customApiKey.trim() || undefined,
      });

      const assistantMsg = {
        id: `ai-${Date.now()}`,
        role: "assistant" as const,
        content: result.reply,
        framingAnalysis: result.framingAnalysis,
        suggestedTitle: result.suggestedTitle,
        suggestedContent: result.suggestedContent,
        suggestedChecklist: result.suggestedChecklist,
        providerUsed: result.providerUsed,
        timestamp: new Date().toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" }),
      };

      setChatMessages((prev) => [...prev, assistantMsg]);
    } catch (err) {
      console.error(err);
      toast({
        title: "Erreur IA",
        description: "Impossible d'obtenir une réponse de l'assistant IA.",
        variant: "destructive",
      });
    } finally {
      setIsChatLoading(false);
    }
  };

  const handleApplyCopilotProposal = (proposal: {
    suggestedTitle?: string;
    suggestedContent?: string;
    suggestedChecklist?: string[];
  }) => {
    if (proposal.suggestedTitle) {
      setTitle(proposal.suggestedTitle);
      setAutoGeneratedTitle(proposal.suggestedTitle);
      setIsManualTitleOpen(true);
    }
    if (proposal.suggestedContent) {
      setContent(proposal.suggestedContent);
    }
    if (proposal.suggestedChecklist && proposal.suggestedChecklist.length > 0) {
      const newItems = proposal.suggestedChecklist.map((item) => ({
        id: `chk-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
        text: item,
        completed: false,
      }));
      setChecklists((prev) => [...prev, ...newItems]);
    }

    setActiveTab("POSTIT");
    toast({
      title: "Cadrage & Mémo appliqués ! 🚀",
      description: "Le titre, le texte rédigé et la checklist ont été intégrés dans votre post-it.",
    });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!content.trim()) {
      toast({
        title: "Contenu requis",
        description: "Veuillez rédiger le contenu de votre mémo.",
        variant: "destructive",
      });
      return;
    }

    // Final title selection: manual title -> auto-generated title -> fallback
    let finalTitle = title.trim();
    if (!finalTitle) {
      finalTitle = autoGeneratedTitle.trim() || extractFaithfulTitle(content.trim(), pillar, associatedSectionLabel);
    }

    if (isEditing && memoToEdit) {
      await updateMemo(memoToEdit.id, {
        title: finalTitle,
        content: content.trim(),
        pillar,
        scope,
        priority,
        associatedSectionHref,
        associatedSectionLabel,
        checklists,
        updatedBy: user?.name || "Utilisateur",
      });
    } else {
      await addMemo({
        title: finalTitle,
        content: content.trim(),
        pillar,
        scope,
        priority,
        associatedSectionHref,
        associatedSectionLabel,
        checklists,
        pinned: false,
        status: "ACTIVE",
        authorName: user?.name || "Utilisateur",
        authorEmail: user?.email || "",
      });
    }

    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-2xl sm:max-w-3xl lg:max-w-4xl max-h-[92vh] overflow-y-auto p-0 border-none bg-transparent shadow-none">
        {/* ═══════════════════════════════════════════════════════════════════════
             DESIGN POST-IT PREMIUM : PAPIER IVOIRE / AMBRE GRC
             ═══════════════════════════════════════════════════════════════════════ */}
        <div
          className="relative rounded-3xl p-6 sm:p-7 transition-all duration-300 border-2 bg-gradient-to-b from-[#FFFDF8] via-[#FEFBF0] to-[#FDF6E2] dark:from-slate-900 dark:via-slate-900/95 dark:to-slate-950 border-amber-300/80 dark:border-amber-600/40 text-slate-800 dark:text-slate-100 shadow-2xl"
          style={{
            boxShadow:
              "0 20px 45px -10px rgba(0, 0, 0, 0.2), 0 0 0 1px rgba(251, 191, 36, 0.15) inset, 0 8px 16px rgba(0,0,0,0.06)",
          }}
        >
          {/* Ruban adhésif / Punaise supérieure */}
          <div className="absolute -top-3 left-1/2 -translate-x-1/2 w-28 h-6 rounded-md backdrop-blur-md border border-amber-400/40 dark:border-amber-600/30 transform -rotate-1 shadow-sm flex items-center justify-center bg-amber-200/50 dark:bg-amber-500/20 z-20">
            <div className="h-2 w-2 rounded-full bg-rose-500 shadow-sm border border-rose-400" />
          </div>

          {/* En-tête du Mémo Post-it */}
          <div className="flex justify-between items-center pb-3 border-b border-amber-200/60 dark:border-slate-800 pt-1">
            <div className="flex items-center gap-2">
              <span className="text-base font-black uppercase tracking-tight flex items-center gap-1.5 text-slate-900 dark:text-white">
                <Pin className="h-4 w-4 fill-current text-rose-500 rotate-12" />
                {isEditing ? "Modifier le Post-it" : "Nouveau Mémo Post-it"}
              </span>
            </div>

            <div className="mr-8">
              <Badge variant="outline" className="text-[9px] font-black uppercase tracking-wider bg-amber-500/10 text-amber-700 dark:text-amber-300 border-amber-300/60 dark:border-amber-700/60">
                📌 Note Active
              </Badge>
            </div>
          </div>

          {/* Sélecteur d'onglets : Note Post-it vs Assistant IA Copilot */}
          <div className="flex items-center gap-2 mt-3 p-1 rounded-2xl bg-amber-500/10 dark:bg-slate-800/80 border border-amber-300/40 dark:border-slate-700">
            <button
              type="button"
              onClick={() => setActiveTab("POSTIT")}
              className={cn(
                "flex-1 py-2 px-3 rounded-xl text-xs font-bold transition-all flex items-center justify-center gap-2",
                activeTab === "POSTIT"
                  ? "bg-white dark:bg-slate-900 text-slate-900 dark:text-white shadow-sm font-black"
                  : "text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white"
              )}
            >
              <Pin className="h-3.5 w-3.5 text-amber-600" />
              <span>Rédiger le Mémo Post-it</span>
            </button>

            <button
              type="button"
              onClick={() => {
                setActiveTab("COPILOT");
                if (chatMessages.length === 1 && content.trim()) {
                  handleSendChatMessage("Cadre mon besoin et améliore ce mémo : " + content.trim());
                }
              }}
              className={cn(
                "flex-1 py-2 px-3 rounded-xl text-xs font-bold transition-all flex items-center justify-center gap-2 relative",
                activeTab === "COPILOT"
                  ? "bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md font-black shadow-indigo-500/20"
                  : "text-indigo-600 dark:text-indigo-400 hover:bg-indigo-500/10"
              )}
            >
              <Bot className="h-4 w-4" />
              <span>🤖 Assistant IA Copilot (ChatGPT GRC)</span>
              <span className="relative flex h-2 w-2">
                <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
              </span>
            </button>
          </div>

          {activeTab === "POSTIT" && (
            <form onSubmit={handleSubmit} className="space-y-4 pt-3.5">
            {/* Aperçu du Titre Généré Automatiquement */}
            {(!isManualTitleOpen || !isEditing) ? (
              <div className="p-3 rounded-2xl bg-amber-500/10 dark:bg-slate-800/80 border border-amber-300/60 dark:border-amber-700/50 flex items-center justify-between gap-3 shadow-xs">
                <div className="flex items-center gap-2.5 min-w-0 flex-1">
                  <div className="p-1.5 rounded-xl bg-amber-500 text-white shrink-0 shadow-sm">
                    {isGeneratingTitle ? (
                      <Loader2 className="h-3.5 w-3.5 animate-spin text-white" />
                    ) : (
                      <Sparkles className="h-3.5 w-3.5" />
                    )}
                  </div>
                  <div className="min-w-0 flex-1">
                    {isGeneratingTitle && (
                      <span className="text-[9px] font-bold text-amber-700 dark:text-amber-300 italic animate-pulse block mb-0.5">
                        Génération du titre en cours...
                      </span>
                    )}
                    <p className="text-xs font-black text-slate-900 dark:text-white truncate">
                      {content.trim()
                        ? (autoGeneratedTitle || "Génération du titre en cours...")
                        : "Rédigez le texte de votre mémo pour générer le titre automatiquement..."}
                    </p>
                  </div>
                </div>

                {content.trim() && (
                  <button
                    type="button"
                    onClick={() => {
                      setTitle(autoGeneratedTitle);
                      setIsManualTitleOpen(true);
                    }}
                    className="p-1.5 rounded-lg text-amber-700 dark:text-amber-400 hover:bg-amber-500/20 text-[10px] font-bold shrink-0 flex items-center gap-1 transition-colors"
                    title="Personnaliser le titre manuellement"
                  >
                    <Edit3 className="h-3 w-3" />
                    <span className="hidden sm:inline">Éditer</span>
                  </button>
                )}
              </div>
            ) : (
              /* Champ Titre Manuel (si ouvert ou en mode édition) */
              <div className="space-y-1">
                <div className="flex justify-between items-center">
                  <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                    Titre du Mémo
                  </label>
                  <button
                    type="button"
                    onClick={() => setTitle(extractFaithfulTitle(content, pillar, associatedSectionLabel))}
                    className="text-[9.5px] font-bold text-amber-700 dark:text-amber-400 hover:underline flex items-center gap-1"
                    title="Régénérer automatiquement le titre à partir du contenu"
                  >
                    <Wand2 className="h-2.5 w-2.5" /> Titre auto
                  </button>
                </div>
                <Input
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="Titre ou objet synthétique du mémo..."
                  className="text-sm font-black tracking-tight rounded-xl bg-white/90 dark:bg-slate-800/90 border-amber-200 dark:border-slate-700 text-slate-900 dark:text-white shadow-xs focus-visible:ring-1 focus-visible:ring-amber-500"
                />
              </div>
            )}

            {/* Badges / Sélecteurs Métier, Portée & Priorité */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
              {/* Volet */}
              <div className="space-y-1">
                <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                  Volet Métier
                </label>
                <select
                  value={pillar}
                  onChange={(e) => setPillar(e.target.value as MemoPillar)}
                  className="w-full text-xs font-bold rounded-xl p-2 bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 outline-none shadow-xs"
                >
                  <option value="LAB_FT">🛡️ LAB / FT</option>
                  <option value="CONFORMITE_REGLEMENTAIRE">⚖️ Conformité Réglementaire</option>
                  <option value="GENERAL">📌 Général</option>
                </select>
              </div>

              {/* Portée */}
              <div className="space-y-1">
                <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                  Portée / Visibilité
                </label>
                <div className="grid grid-cols-2 gap-1 p-1 rounded-xl bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 shadow-xs">
                  <button
                    type="button"
                    onClick={() => setScope("COLLABORATIVE")}
                    className={cn(
                      "py-1 px-1.5 text-[10px] font-bold rounded-lg transition-all flex items-center justify-center gap-1",
                      scope === "COLLABORATIVE"
                        ? "bg-indigo-600 text-white shadow-sm"
                        : "text-slate-500 hover:text-slate-900 dark:hover:text-white"
                    )}
                  >
                    <Users className="h-3 w-3" />
                    Équipe
                  </button>
                  <button
                    type="button"
                    onClick={() => setScope("PRIVATE")}
                    className={cn(
                      "py-1 px-1.5 text-[10px] font-bold rounded-lg transition-all flex items-center justify-center gap-1",
                      scope === "PRIVATE"
                        ? "bg-slate-800 dark:bg-slate-700 text-white shadow-sm"
                        : "text-slate-500 hover:text-slate-900 dark:hover:text-white"
                    )}
                  >
                    <User className="h-3 w-3" />
                    Privé
                  </button>
                </div>
              </div>

              {/* Priorité */}
              <div className="space-y-1">
                <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                  Niveau de Priorité
                </label>
                <select
                  value={priority}
                  onChange={(e) => setPriority(e.target.value as MemoPriority)}
                  className="w-full text-xs font-bold rounded-xl p-2 bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 outline-none shadow-xs"
                >
                  <option value="URGENT">🚨 Urgent / Bloquant</option>
                  <option value="ATTENTION">⚡ Attention</option>
                  <option value="INFO">🟢 Information</option>
                </select>
              </div>
            </div>

            {/* Section Applicative Associée */}
            <div className="space-y-1">
              <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider flex items-center gap-1">
                <Layers className="h-3 w-3 text-indigo-500" />
                Section Applicative Associée
              </label>
              <select
                value={associatedSectionHref}
                onChange={(e) => handleSectionChange(e.target.value)}
                className="w-full text-xs font-semibold rounded-xl p-2 bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 outline-none shadow-xs truncate"
              >
                {APP_SECTIONS.map((sec) => (
                  <option key={sec.href} value={sec.href}>
                    [{sec.group}] — {sec.label}
                  </option>
                ))}
              </select>
            </div>

            {/* Zone de texte & Barre d'Outils IA */}
            <div className="space-y-2">
              <div className="flex justify-between items-center flex-wrap gap-2">
                <label className="text-xs sm:text-sm font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
                  Contenu du mémo <span className="text-rose-500">*</span>
                </label>

                {/* Boutons Reformulation IA */}
                <div className="flex items-center gap-1 bg-amber-500/10 dark:bg-slate-800 p-1 rounded-xl border border-amber-300/40 dark:border-slate-700 flex-wrap">
                  <button
                    type="button"
                    onClick={() => {
                      setActiveTab("COPILOT");
                      if (content.trim()) {
                        handleSendChatMessage("Cadre mon besoin et améliore ce mémo : " + content.trim());
                      }
                    }}
                    className="px-2.5 py-1 text-[10px] font-black rounded-lg bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white flex items-center gap-1 shadow-xs transition-all mr-1"
                    title="Ouvrir l'Assistant Copilot pour dialoguer et cadrer ce mémo comme dans ChatGPT"
                  >
                    <Bot className="h-3 w-3" />
                    <span>Chat Copilot ➔</span>
                  </button>

                  <span className="text-[10px] font-black uppercase text-amber-700 dark:text-amber-400 px-1.5 flex items-center gap-1">
                    <Sparkles className="h-3 w-3 text-amber-500 animate-pulse" /> Rapide :
                  </span>
                  <button
                    type="button"
                    disabled={isReformulating || !content.trim()}
                    onClick={() => handleReformulate("FORMAL")}
                    className={cn(
                      "px-2.5 py-1 text-[10px] font-bold rounded-lg transition-all shadow-xs disabled:opacity-40 flex items-center gap-1",
                      aiStyle === "FORMAL" && showAiPreview
                        ? "bg-amber-500 text-white font-extrabold"
                        : "bg-white dark:bg-slate-900 hover:bg-amber-500 hover:text-white text-slate-700 dark:text-slate-200"
                    )}
                    title="Ton formel et soigné pour note de direction"
                  >
                    {isReformulating && aiStyle === "FORMAL" ? <Loader2 className="h-2.5 w-2.5 animate-spin" /> : "👔 Formel"}
                  </button>
                  <button
                    type="button"
                    disabled={isReformulating || !content.trim()}
                    onClick={() => handleReformulate("SYNTHETIC")}
                    className={cn(
                      "px-2.5 py-1 text-[10px] font-bold rounded-lg transition-all shadow-xs disabled:opacity-40 flex items-center gap-1",
                      aiStyle === "SYNTHETIC" && showAiPreview
                        ? "bg-amber-500 text-white font-extrabold"
                        : "bg-white dark:bg-slate-900 hover:bg-amber-500 hover:text-white text-slate-700 dark:text-slate-200"
                    )}
                    title="Synthèse en bullet points orientée action"
                  >
                    {isReformulating && aiStyle === "SYNTHETIC" ? <Loader2 className="h-2.5 w-2.5 animate-spin" /> : "⚡ Synthétique"}
                  </button>
                  <button
                    type="button"
                    disabled={isReformulating || !content.trim()}
                    onClick={() => handleReformulate("LEGAL")}
                    className={cn(
                      "px-2.5 py-1 text-[10px] font-bold rounded-lg transition-all shadow-xs disabled:opacity-40 flex items-center gap-1",
                      aiStyle === "LEGAL" && showAiPreview
                        ? "bg-amber-500 text-white font-extrabold"
                        : "bg-white dark:bg-slate-900 hover:bg-amber-500 hover:text-white text-slate-700 dark:text-slate-200"
                    )}
                    title="Formulation réglementaire rigoureuse LCB-FT / CGA"
                  >
                    {isReformulating && aiStyle === "LEGAL" ? <Loader2 className="h-2.5 w-2.5 animate-spin" /> : "⚖️ Réglementaire"}
                  </button>
                  <button
                    type="button"
                    disabled={isReformulating || !content.trim()}
                    onClick={() => handleReformulate("CLARITY")}
                    className={cn(
                      "px-2.5 py-1 text-[10px] font-bold rounded-lg transition-all shadow-xs disabled:opacity-40 flex items-center gap-1",
                      aiStyle === "CLARITY" && showAiPreview
                        ? "bg-amber-500 text-white font-extrabold"
                        : "bg-white dark:bg-slate-900 hover:bg-amber-500 hover:text-white text-slate-700 dark:text-slate-200"
                    )}
                    title="Correction orthographe, syntaxe et clarté optimale"
                  >
                    {isReformulating && aiStyle === "CLARITY" ? <Loader2 className="h-2.5 w-2.5 animate-spin" /> : "✨ Clarté"}
                  </button>
                  <button
                    type="button"
                    disabled={isReformulating || !content.trim()}
                    onClick={() => handleReformulate("CHECKLIST")}
                    className={cn(
                      "px-2.5 py-1 text-[10px] font-bold rounded-lg transition-all shadow-xs disabled:opacity-40 flex items-center gap-1",
                      aiStyle === "CHECKLIST" && showAiPreview
                        ? "bg-amber-500 text-white font-extrabold"
                        : "bg-white dark:bg-slate-900 hover:bg-amber-500 hover:text-white text-slate-700 dark:text-slate-200"
                    )}
                    title="Extraction de plan de contrôle et checklist d'actions"
                  >
                    {isReformulating && aiStyle === "CHECKLIST" ? <Loader2 className="h-2.5 w-2.5 animate-spin" /> : "☑️ Checklist"}
                  </button>
                </div>
              </div>

              <Textarea
                value={content}
                onChange={(e) => setContent(e.target.value)}
                placeholder="Rédigez vos observations, instructions, questions ou consignes ici... Le titre synthétique sera automatiquement généré."
                rows={8}
                className="text-sm sm:text-base rounded-2xl font-medium leading-relaxed bg-white/95 dark:bg-slate-800/95 border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 shadow-xs resize-y focus-visible:ring-1 focus-visible:ring-amber-500 p-3.5"
                required
              />
            </div>

            {/* Prévisualisation Reformulation IA */}
            {showAiPreview && aiSuggestion && (
              <div className="p-4 rounded-2xl bg-white dark:bg-slate-900 border-2 border-amber-400 dark:border-amber-500/60 shadow-lg space-y-3 animate-in fade-in duration-200">
                <div className="flex justify-between items-center gap-2 flex-wrap">
                  <span className="text-xs font-black uppercase text-amber-700 dark:text-amber-400 flex items-center gap-1.5">
                    <Sparkles className="h-4 w-4 text-amber-500" />
                    Amélioration IA (
                    {aiStyle === "FORMAL"
                      ? "👔 Formel"
                      : aiStyle === "SYNTHETIC"
                      ? "⚡ Synthétique"
                      : aiStyle === "LEGAL"
                      ? "⚖️ Réglementaire"
                      : aiStyle === "CLARITY"
                      ? "✨ Clarté & Orthographe"
                      : "☑️ Checklist & Actions"}
                    )
                  </span>
                  <div className="flex items-center gap-1.5">
                    <Button
                      type="button"
                      size="sm"
                      onClick={handleApplyAiSuggestion}
                      className="h-7 px-3 bg-amber-500 hover:bg-amber-600 text-white rounded-lg text-xs font-black gap-1 shadow-xs"
                    >
                      <Check className="h-3.5 w-3.5" /> Insérer cette version
                    </Button>
                    {aiSuggestion.checklist && aiSuggestion.checklist.length > 0 && (
                      <Button
                        type="button"
                        size="sm"
                        variant="outline"
                        onClick={handleImportAiChecklist}
                        className="h-7 px-3 border-emerald-400 hover:bg-emerald-50 dark:hover:bg-slate-800 text-emerald-700 dark:text-emerald-300 rounded-lg text-xs font-bold gap-1"
                      >
                        <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" /> + Checklist ({aiSuggestion.checklist.length})
                      </Button>
                    )}
                    <button
                      type="button"
                      onClick={() => setShowAiPreview(false)}
                      className="text-xs text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 p-1 rounded-md"
                    >
                      ✕
                    </button>
                  </div>
                </div>

                {aiSuggestion.title && (
                  <p className="text-xs sm:text-sm font-bold text-slate-800 dark:text-slate-200">
                    <span className="text-slate-400 font-normal">Titre suggéré :</span> {aiSuggestion.title}
                  </p>
                )}

                <div className="text-xs sm:text-sm text-slate-800 dark:text-slate-200 whitespace-pre-line leading-relaxed font-medium bg-amber-50/70 dark:bg-slate-800/60 p-3.5 rounded-xl border border-amber-200/70 dark:border-slate-700">
                  {aiSuggestion.text}
                </div>

                {aiSuggestion.checklist && aiSuggestion.checklist.length > 0 && (
                  <div className="p-3 bg-emerald-50/60 dark:bg-emerald-950/20 border border-emerald-300/50 dark:border-emerald-800/50 rounded-xl space-y-1.5">
                    <div className="flex justify-between items-center">
                      <span className="text-[11px] font-black uppercase text-emerald-700 dark:text-emerald-400 flex items-center gap-1">
                        <CheckCircle2 className="h-3.5 w-3.5" /> Actions suggérées à cocher :
                      </span>
                      <button
                        type="button"
                        onClick={handleImportAiChecklist}
                        className="text-[11px] font-bold text-emerald-600 hover:underline"
                      >
                        Tout importer dans la checklist ➔
                      </button>
                    </div>
                    <ul className="text-xs text-slate-700 dark:text-slate-300 space-y-1">
                      {aiSuggestion.checklist.map((item, idx) => (
                        <li key={idx} className="flex items-start gap-1.5">
                          <span className="text-emerald-500 font-bold">☑</span>
                          <span>{item}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            )}

            {/* Checklist / Actions */}
            <div className="space-y-2 pt-1 border-t border-amber-200/60 dark:border-slate-800">
              <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider flex items-center gap-1">
                <CheckCircle2 className="h-3 w-3 text-emerald-500" />
                Checklist / Actions à vérifier
              </label>

              <div className="flex gap-2">
                <Input
                  value={checklistInput}
                  onChange={(e) => setChecklistInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      e.preventDefault();
                      handleAddChecklistItem();
                    }
                  }}
                  placeholder="Ajouter une action (ex: Contrôler la pièce d'identité)..."
                  className="text-xs rounded-xl h-8 bg-white/90 dark:bg-slate-800/90 border-amber-200 dark:border-slate-700"
                />
                <Button
                  type="button"
                  size="sm"
                  onClick={handleAddChecklistItem}
                  className="h-8 px-3 rounded-xl bg-amber-500/20 hover:bg-amber-500/30 text-amber-800 dark:text-amber-200 text-xs font-bold shrink-0"
                >
                  <Plus className="h-3.5 w-3.5 mr-1" />
                  Ajouter
                </Button>
              </div>

              {checklists.length > 0 && (
                <div className="space-y-1 max-h-28 overflow-y-auto pr-1">
                  {checklists.map((chk) => (
                    <div
                      key={chk.id}
                      className="flex items-center justify-between gap-2 px-2.5 py-1.5 bg-white/80 dark:bg-slate-800/80 rounded-xl border border-amber-200/40 dark:border-slate-700 text-xs"
                    >
                      <span className="truncate font-medium text-slate-700 dark:text-slate-300">
                        • {chk.text}
                      </span>
                      <button
                        type="button"
                        onClick={() => handleRemoveChecklistItem(chk.id)}
                        className="text-slate-400 hover:text-rose-500 p-1"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Pied du Post-it */}
            <div className="pt-3 border-t border-amber-200/60 dark:border-slate-800 flex justify-between items-center gap-2">
              <Button
                type="button"
                variant="outline"
                onClick={onClose}
                className="h-9 px-4 rounded-xl text-xs font-semibold bg-white/80 dark:bg-slate-800 border-amber-200 dark:border-slate-700"
              >
                Annuler
              </Button>
              <Button
                type="submit"
                className="h-9 px-5 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-white text-xs font-black shadow-md shadow-amber-500/20"
              >
                {isEditing ? "Enregistrer les modifications" : "Épingler le Post-it 📌"}
              </Button>
            </div>
          </form>
        )}

        {/* ═══════════════════════════════════════════════════════════════════════
             MODE 2 : ASSISTANT IA COPILOT (STYLE CHATGPT / CADRAGE DU BESOIN)
             ═══════════════════════════════════════════════════════════════════════ */}
        {activeTab === "COPILOT" && (
          <div className="space-y-4 pt-3.5">
            {/* En-tête Copilot avec Statut & Clé API */}
            <div className="p-3.5 rounded-2xl bg-gradient-to-r from-indigo-500/10 via-purple-500/10 to-amber-500/10 dark:bg-slate-800/90 border border-indigo-200/60 dark:border-indigo-900/50 flex justify-between items-center flex-wrap gap-2">
              <div className="flex items-center gap-2.5">
                <div className="p-2 rounded-xl bg-gradient-to-br from-indigo-600 to-purple-600 text-white shadow-md shadow-indigo-500/20">
                  <Bot className="h-5 w-5" />
                </div>
                <div>
                  <h4 className="text-xs font-black uppercase tracking-tight text-slate-900 dark:text-white flex items-center gap-2">
                    Copilot IA GRC (Style ChatGPT)
                    <Badge className="bg-emerald-500 text-white text-[8.5px] font-black uppercase px-2 py-0.2 border-none">
                      Prêt
                    </Badge>
                  </h4>
                  <p className="text-[11px] text-slate-500 dark:text-slate-400">
                    Cadrage de besoin, diagnostic réglementaire et rédaction assistée
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setShowKeyConfig(!showKeyConfig)}
                  className="px-2.5 py-1 text-[11px] font-bold rounded-lg border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 hover:bg-white dark:hover:bg-slate-800 flex items-center gap-1 transition-all"
                  title="Configurer une clé personnelle Groq, Gemini ou OpenAI"
                >
                  <KeyRound className="h-3 w-3 text-amber-500" />
                  <span>{customApiKey ? "Clé active ✓" : "Clé API (Optionnel)"}</span>
                </button>
              </div>
            </div>

            {/* Panneau de configuration Clé API (dépliable) */}
            {showKeyConfig && (
              <div className="p-3.5 bg-white dark:bg-slate-900 rounded-2xl border border-indigo-200 dark:border-slate-800 space-y-2 animate-in fade-in duration-200">
                <div className="flex justify-between items-center">
                  <span className="text-xs font-black uppercase text-indigo-700 dark:text-indigo-400 flex items-center gap-1.5">
                    <KeyRound className="h-3.5 w-3.5" /> Clé API Personnelle (Groq, Gemini, OpenAI)
                  </span>
                  <button
                    type="button"
                    onClick={() => setShowKeyConfig(false)}
                    className="text-xs text-slate-400 hover:text-slate-600"
                  >
                    ✕
                  </button>
                </div>
                <p className="text-[11px] text-slate-500 dark:text-slate-400">
                  Optionnel : Entrez votre clé Groq (commence par <code className="font-mono text-indigo-600">gsk_</code>), Gemini (<code className="font-mono text-indigo-600">AIza...</code>) ou OpenAI (<code className="font-mono text-indigo-600">sk-...</code>). Si vous ne renseignez pas de clé, le moteur cognitif autonome GRC prend le relais à 100%.
                </p>
                <div className="flex gap-2">
                  <Input
                    value={customApiKey}
                    onChange={(e) => setCustomApiKey(e.target.value)}
                    placeholder="Ex: gsk_... ou AIza... ou sk-..."
                    className="text-xs h-8 rounded-xl font-mono"
                  />
                  <Button
                    type="button"
                    size="sm"
                    onClick={() => handleSaveApiKey(customApiKey)}
                    className="h-8 px-3 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold shrink-0"
                  >
                    Enregistrer
                  </Button>
                </div>
              </div>
            )}

            {/* Suggestions Rapides 1-Clic */}
            <div className="space-y-1.5">
              <span className="text-[10px] font-black uppercase tracking-wider text-slate-500 flex items-center gap-1">
                <Sparkles className="h-3 w-3 text-indigo-500" /> Cadrages rapides en 1 clic :
              </span>
              <div className="flex items-center gap-1.5 flex-wrap">
                <button
                  type="button"
                  disabled={isChatLoading}
                  onClick={() =>
                    handleSendChatMessage(
                      content.trim()
                        ? `Cadre mon besoin et améliore ce mémo : "${content.trim()}"`
                        : "Cadre mon besoin : aide-moi à structurer une note de conformité sur un problème de vérification KYC client non complété."
                    )
                  }
                  className="px-2.5 py-1 text-[11px] font-bold rounded-xl bg-white dark:bg-slate-800 border border-indigo-200 dark:border-indigo-900/60 text-indigo-700 dark:text-indigo-300 hover:bg-indigo-50 dark:hover:bg-slate-700 shadow-2xs transition-all flex items-center gap-1 disabled:opacity-50"
                >
                  🎯 Cadre mon besoin brut
                </button>

                <button
                  type="button"
                  disabled={isChatLoading}
                  onClick={() =>
                    handleSendChatMessage(
                      "Rédige une note d'alerte et de vigilance LCB-FT sur un client effectuant des versements suspects en espèces dépassant les seuils autorisés."
                    )
                  }
                  className="px-2.5 py-1 text-[11px] font-bold rounded-xl bg-white dark:bg-slate-800 border border-amber-200 dark:border-amber-900/60 text-amber-700 dark:text-amber-300 hover:bg-amber-50 dark:hover:bg-slate-700 shadow-2xs transition-all flex items-center gap-1 disabled:opacity-50"
                >
                  🛡️ Alerte LCB-FT & Espèces
                </button>

                <button
                  type="button"
                  disabled={isChatLoading}
                  onClick={() =>
                    handleSendChatMessage(
                      "Formule une consigne ferme et claire pour les agences commerciales concernant l'obligation d'extraits RNE récents de moins de 3 mois pour toute personne morale."
                    )
                  }
                  className="px-2.5 py-1 text-[11px] font-bold rounded-xl bg-white dark:bg-slate-800 border border-purple-200 dark:border-purple-900/60 text-purple-700 dark:text-purple-300 hover:bg-purple-50 dark:hover:bg-slate-700 shadow-2xs transition-all flex items-center gap-1 disabled:opacity-50"
                >
                  ⚡ Consigne pour les agences
                </button>

                <button
                  type="button"
                  disabled={isChatLoading}
                  onClick={() =>
                    handleSendChatMessage(
                      "Détaille l'argumentaire juridique et réglementaire basé sur les circulaires CTAF et le Code des Assurances pour bloquer une transaction suspecte."
                    )
                  }
                  className="px-2.5 py-1 text-[11px] font-bold rounded-xl bg-white dark:bg-slate-800 border border-emerald-200 dark:border-emerald-900/60 text-emerald-700 dark:text-emerald-300 hover:bg-emerald-50 dark:hover:bg-slate-700 shadow-2xs transition-all flex items-center gap-1 disabled:opacity-50"
                >
                  ⚖️ Réglementation CTAF / CGA
                </button>

                <button
                  type="button"
                  disabled={isChatLoading}
                  onClick={() =>
                    handleSendChatMessage(
                      "Génère une checklist opérationnelle exhaustive de contrôle sur pièces pour l'audit d'un contrat d'assurance."
                    )
                  }
                  className="px-2.5 py-1 text-[11px] font-bold rounded-xl bg-white dark:bg-slate-800 border border-blue-200 dark:border-blue-900/60 text-blue-700 dark:text-blue-300 hover:bg-blue-50 dark:hover:bg-slate-700 shadow-2xs transition-all flex items-center gap-1 disabled:opacity-50"
                >
                  ☑️ Plan d'action & Checklist
                </button>
              </div>
            </div>

            {/* Fil de discussion interactif */}
            <div className="rounded-2xl border border-amber-200/80 dark:border-slate-800 bg-white/60 dark:bg-slate-900/60 p-4 max-h-[460px] overflow-y-auto space-y-4">
              {chatMessages.map((msg) => (
                <div
                  key={msg.id}
                  className={cn(
                    "flex flex-col gap-1.5 animate-in fade-in duration-200",
                    msg.role === "user" ? "items-end" : "items-start"
                  )}
                >
                  {/* Header du message */}
                  <div className="flex items-center gap-2 text-[10px] text-slate-400 font-bold px-1">
                    {msg.role === "user" ? (
                      <span>Vous</span>
                    ) : (
                      <span className="flex items-center gap-1 text-indigo-600 dark:text-indigo-400 font-black">
                        <Bot className="h-3 w-3" /> Copilot IA GRC
                        {msg.providerUsed && (
                          <Badge variant="outline" className="text-[8px] font-medium border-indigo-200 dark:border-indigo-800">
                            {msg.providerUsed}
                          </Badge>
                        )}
                      </span>
                    )}
                    <span>· {msg.timestamp}</span>
                  </div>

                  {/* Corps du message */}
                  {msg.role === "user" ? (
                    <div className="max-w-[85%] rounded-2xl rounded-tr-sm bg-gradient-to-r from-indigo-600 to-indigo-700 text-white p-3.5 text-xs sm:text-sm font-medium shadow-sm whitespace-pre-line leading-relaxed">
                      {msg.content}
                    </div>
                  ) : (
                    <div className="w-full rounded-2xl rounded-tl-sm bg-white dark:bg-slate-900 border border-indigo-100 dark:border-slate-800 p-4 space-y-3.5 shadow-sm text-xs sm:text-sm">
                      <p className="text-slate-800 dark:text-slate-200 leading-relaxed font-medium">
                        {msg.content}
                      </p>

                      {/* 🧠 Cadrage du besoin & Diagnostic */}
                      {msg.framingAnalysis && (
                        <div className="p-3.5 rounded-xl bg-gradient-to-r from-amber-500/10 via-amber-500/5 to-indigo-500/10 border border-amber-300/60 dark:border-amber-700/50 space-y-2">
                          <span className="text-[11px] font-black uppercase text-amber-800 dark:text-amber-300 flex items-center gap-1.5">
                            <ShieldAlert className="h-3.5 w-3.5 text-amber-600" /> Cadrage du besoin & Diagnostic réglementaire
                          </span>
                          <div className="text-xs text-slate-700 dark:text-slate-300 whitespace-pre-line leading-relaxed font-medium">
                            {msg.framingAnalysis}
                          </div>
                        </div>
                      )}

                      {/* 📝 Proposition de Mémo rédigé */}
                      {msg.suggestedContent && (
                        <div className="p-3.5 rounded-xl bg-amber-50/70 dark:bg-slate-800/80 border-2 border-amber-400 dark:border-amber-600 space-y-2">
                          <div className="flex justify-between items-center gap-2 flex-wrap">
                            <span className="text-[11px] font-black uppercase text-slate-900 dark:text-white flex items-center gap-1.5">
                              <Pin className="h-3 w-3 text-rose-500" /> Mémo proposé :{" "}
                              <span className="text-indigo-600 dark:text-indigo-400">{msg.suggestedTitle}</span>
                            </span>
                            <button
                              type="button"
                              onClick={() => {
                                navigator.clipboard.writeText(`${msg.suggestedTitle}\n\n${msg.suggestedContent}`);
                                toast({ title: "Texte copié !", description: "Le mémo a été copié dans le presse-papier." });
                              }}
                              className="text-[10px] font-bold text-slate-500 hover:text-slate-800 dark:hover:text-white flex items-center gap-1"
                            >
                              <Copy className="h-3 w-3" /> Copier
                            </button>
                          </div>

                          <p className="text-xs sm:text-[13px] text-slate-800 dark:text-slate-200 whitespace-pre-line leading-relaxed font-medium bg-white/80 dark:bg-slate-900/80 p-3 rounded-lg border border-amber-200/60 dark:border-slate-700">
                            {msg.suggestedContent}
                          </p>

                          {/* Checklist suggérée */}
                          {msg.suggestedChecklist && msg.suggestedChecklist.length > 0 && (
                            <div className="pt-2 border-t border-amber-200/60 dark:border-slate-700 space-y-1">
                              <span className="text-[10px] font-black uppercase text-emerald-700 dark:text-emerald-400 flex items-center gap-1">
                                <CheckCircle2 className="h-3 w-3" /> Checklist d'actions ({msg.suggestedChecklist.length}) :
                              </span>
                              <ul className="text-xs text-slate-700 dark:text-slate-300 space-y-1">
                                {msg.suggestedChecklist.map((item, idx) => (
                                  <li key={idx} className="flex items-start gap-1.5">
                                    <span className="text-emerald-500 font-bold">☑</span>
                                    <span>{item}</span>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}

                          {/* Bouton d'application directe au Post-it */}
                          <div className="pt-2">
                            <Button
                              type="button"
                              onClick={() =>
                                handleApplyCopilotProposal({
                                  suggestedTitle: msg.suggestedTitle,
                                  suggestedContent: msg.suggestedContent,
                                  suggestedChecklist: msg.suggestedChecklist,
                                })
                              }
                              className="w-full h-8 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white font-black text-xs rounded-xl gap-1.5 shadow-md shadow-emerald-600/20"
                            >
                              <Check className="h-4 w-4" /> Appliquer directement à mon Mémo Post-it ➔
                            </Button>
                          </div>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}

              {isChatLoading && (
                <div className="flex items-center gap-2 p-3 bg-indigo-50/50 dark:bg-slate-800/50 rounded-xl text-xs text-indigo-700 dark:text-indigo-300 font-bold animate-pulse">
                  <Loader2 className="h-4 w-4 animate-spin text-indigo-600" />
                  <span>L'IA analyse votre situation, cadre votre besoin et rédige le mémo...</span>
                </div>
              )}
            </div>

            {/* Zone de saisie conversationnelle */}
            <div className="space-y-2">
              <div className="flex gap-2">
                <Textarea
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && !e.shiftKey) {
                      e.preventDefault();
                      handleSendChatMessage();
                    }
                  }}
                  placeholder="Décrivez votre besoin brut ou posez votre question à l'IA (comme sur ChatGPT)... Ex: J'ai un client étranger qui refuse de justifier ses fonds, que doit-on faire et consigner ?"
                  rows={3}
                  className="text-xs sm:text-sm rounded-2xl bg-white/95 dark:bg-slate-800/95 border-indigo-200 dark:border-slate-700 resize-none font-medium p-3"
                />
                <Button
                  type="button"
                  disabled={isChatLoading || !chatInput.trim()}
                  onClick={() => handleSendChatMessage()}
                  className="h-auto px-4 rounded-2xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 text-white font-black text-xs gap-1.5 shrink-0 shadow-md shadow-indigo-600/20 disabled:opacity-40"
                >
                  {isChatLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
                  <span className="hidden sm:inline">Envoyer</span>
                </Button>
              </div>

              <div className="flex justify-between items-center text-[10px] text-slate-400 px-1">
                <span>Appuyez sur Entrée pour envoyer · Maj + Entrée pour nouvelle ligne</span>
                <button
                  type="button"
                  onClick={() => setActiveTab("POSTIT")}
                  className="text-indigo-600 dark:text-indigo-400 hover:underline font-bold"
                >
                  Retourner au Post-it ➔
                </button>
              </div>
            </div>
          </div>
        )}

          {/* Effet d'ombre de coin replié en bas à droite */}
          <div
            className="absolute bottom-0 right-0 w-6 h-6 pointer-events-none rounded-br-3xl opacity-30"
            style={{
              background: "linear-gradient(135deg, transparent 50%, rgba(0,0,0,0.15) 50%)",
            }}
          />
        </div>
      </DialogContent>
    </Dialog>
  );
};
