"use client";

import React, { useState, useEffect, useRef } from "react";
import {
  Dialog,
  DialogContent,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Pin,
  Sparkles,
  Plus,
  Trash2,
  Users,
  User,
  Layers,
  CheckCircle2,
  Check,
  Loader2,
  Edit3,
  KeyRound,
  RotateCcw,
  Wand2,
  Bot,
  Send,
  MessageSquare,
  ArrowRight,
  ShieldCheck,
  AlertTriangle,
  FileText,
  X,
} from "lucide-react";
import { ComplianceMemo, MemoPillar, MemoScope, MemoPriority, APP_SECTIONS } from "@/types/memo";
import { useMemos } from "@/contexts/MemoContext";
import { useUser } from "@/contexts/UserContext";
import {
  improveMemoWithAIAction,
  generateAutoTitleAction,
  chatWithMemoAIAction,
} from "@/app/(app)/memos/actions";
import { extractFaithfulTitle } from "@/lib/memoTitleGenerator";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

interface MemoEditorModalProps {
  isOpen: boolean;
  onClose: () => void;
  memoToEdit: ComplianceMemo | null;
  defaultSectionHref?: string;
  defaultSectionLabel?: string;
}

export const MemoEditorModal: React.FC<MemoEditorModalProps> = ({
  isOpen,
  onClose,
  memoToEdit,
  defaultSectionHref = "/dashboard",
  defaultSectionLabel = "Dashboard Général",
}) => {
  const { addMemo, updateMemo } = useMemos();
  const { user } = useUser();
  const { toast } = useToast();

  const isEditing = Boolean(memoToEdit && memoToEdit.id);

  // Tab: "postit" (formulaire note) vs "chatbot" (chat conversationnel style ChatGPT)
  const [activeTab, setActiveTab] = useState<"postit" | "chatbot">("postit");

  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [pillar, setPillar] = useState<MemoPillar>("LAB_FT");
  const [scope, setScope] = useState<MemoScope>("COLLABORATIVE");
  const [priority, setPriority] = useState<MemoPriority>("ATTENTION");
  const [associatedSectionHref, setAssociatedSectionHref] = useState(defaultSectionHref);
  const [associatedSectionLabel, setAssociatedSectionLabel] = useState(defaultSectionLabel);
  const [checklistInput, setChecklistInput] = useState("");
  const [checklists, setChecklists] = useState<{ id: string; text: string; completed: boolean }[]>([]);

  // State to allow manual title editing
  const [isManualTitleOpen, setIsManualTitleOpen] = useState(false);

  // Auto-generated Title state
  const [autoGeneratedTitle, setAutoGeneratedTitle] = useState("");
  const [isGeneratingTitle, setIsGeneratingTitle] = useState(false);

  // AI Improvement states (Mode direct)
  const [isImproving, setIsImproving] = useState(false);
  const [improvedSuccess, setImprovedSuccess] = useState(false);
  const [undoBackup, setUndoBackup] = useState<{
    title: string;
    content: string;
    checklists: { id: string; text: string; completed: boolean }[];
  } | null>(null);

  // Conversational Chatbot states (Style ChatGPT)
  const [chatInput, setChatInput] = useState("");
  const [isChatSending, setIsChatSending] = useState(false);
  const [chatMessages, setChatMessages] = useState<Array<{
    id: string;
    role: "user" | "assistant";
    content: string;
    framingAnalysis?: string;
    suggestedTitle?: string;
    suggestedContent?: string;
    suggestedChecklist?: string[];
    providerUsed?: string;
  }>>([]);
  const [lastGeneratedDraft, setLastGeneratedDraft] = useState<{
    title: string;
    content: string;
    checklist: string[];
  } | null>(null);

  const chatBottomRef = useRef<HTMLDivElement>(null);

  // Custom API key configuration
  const [customApiKey, setCustomApiKey] = useState("");
  const [showKeyConfig, setShowKeyConfig] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const savedKey = localStorage.getItem("COMPLIANCE_AI_KEY") || "";
      setCustomApiKey(savedKey);
    }
  }, []);

  useEffect(() => {
    if (memoToEdit) {
      setTitle(memoToEdit.title || "");
      setContent(memoToEdit.content || "");
      setPillar(memoToEdit.pillar || "LAB_FT");
      setScope(memoToEdit.scope || "COLLABORATIVE");
      setPriority(memoToEdit.priority || "ATTENTION");
      setAssociatedSectionHref(memoToEdit.associatedSectionHref || defaultSectionHref);
      setAssociatedSectionLabel(memoToEdit.associatedSectionLabel || defaultSectionLabel);
      setChecklists(memoToEdit.checklists || []);
      setIsManualTitleOpen(true);
    } else {
      setTitle("");
      setContent("");
      setPillar("LAB_FT");
      setScope("COLLABORATIVE");
      setPriority("ATTENTION");
      setAssociatedSectionHref(defaultSectionHref);
      setAssociatedSectionLabel(defaultSectionLabel);
      setChecklists([]);
      setIsManualTitleOpen(false);
      setAutoGeneratedTitle("");
    }
    setImprovedSuccess(false);
    setUndoBackup(null);
    setActiveTab("postit");
  }, [memoToEdit, defaultSectionHref, defaultSectionLabel, isOpen]);

  // Initial welcome message in conversational chatbot
  useEffect(() => {
    if (isOpen && chatMessages.length === 0) {
      setChatMessages([
        {
          id: "welcome-1",
          role: "assistant",
          content:
            "Bonjour ! Je suis votre Copilot IA Conformité. Décrivez-moi librement votre problème, anomalie ou situation en langage naturel (comme sur ChatGPT). Je vais cadrer votre besoin, analyser les risques réglementaires, structurer votre note avec des points clairs et vous préparer le Post-it complet.",
        },
      ]);
    }
  }, [isOpen, chatMessages.length]);

  // Scroll to bottom of chat when messages update
  useEffect(() => {
    if (activeTab === "chatbot") {
      chatBottomRef.current?.scrollIntoView({ behavior: "smooth" });
    }
  }, [chatMessages, isChatSending, activeTab]);

  // Debounced intelligent AI title synthesizer triggered while typing in post-it mode
  useEffect(() => {
    if (!content.trim()) {
      setAutoGeneratedTitle("");
      setIsGeneratingTitle(false);
      return;
    }

    const immediateTitle = extractFaithfulTitle(content, pillar, associatedSectionLabel);
    setAutoGeneratedTitle(immediateTitle);

    if (content.trim().length > 15 && !title) {
      setIsGeneratingTitle(true);
      const timer = setTimeout(async () => {
        try {
          const res = await generateAutoTitleAction({
            content: content.trim(),
            pillar,
            sectionLabel: associatedSectionLabel,
          });
          if (res && res.title && res.title.trim()) {
            setAutoGeneratedTitle(res.title.trim());
          }
        } catch (e) {
          console.warn("Async title generator error:", e);
        } finally {
          setIsGeneratingTitle(false);
        }
      }, 500);

      return () => clearTimeout(timer);
    }
  }, [content, pillar, associatedSectionLabel, title]);

  const handleAddChecklistItem = () => {
    if (!checklistInput.trim()) return;
    setChecklists((prev) => [
      ...prev,
      {
        id: `chk-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
        text: checklistInput.trim(),
        completed: false,
      },
    ]);
    setChecklistInput("");
  };

  const handleRemoveChecklistItem = (id: string) => {
    setChecklists((prev) => prev.filter((item) => item.id !== id));
  };

  const handleSectionChange = (href: string) => {
    const selected = APP_SECTIONS.find((s) => s.href === href);
    setAssociatedSectionHref(href);
    setAssociatedSectionLabel(selected ? selected.label : "Section personnalisée");
  };

  const handleSaveApiKey = (key: string) => {
    setCustomApiKey(key);
    if (typeof window !== "undefined") {
      localStorage.setItem("COMPLIANCE_AI_KEY", key.trim());
    }
    toast({
      title: "Clé API enregistrée",
      description: "Votre clé a été sauvegardée localement dans votre navigateur.",
    });
    setShowKeyConfig(false);
  };

  // ─── AMÉLIORATION DIRECTE 1-CLIC ───────────────────────────────────────────
  const handleImproveWithAI = async () => {
    if (!content.trim()) {
      toast({
        title: "Notes requises",
        description: "Veuillez d'abord rédiger vos notes ou vos points bruts dans le mémo.",
        variant: "destructive",
      });
      return;
    }

    setIsImproving(true);
    setUndoBackup({
      title: title || autoGeneratedTitle,
      content,
      checklists: [...checklists],
    });

    try {
      const result = await improveMemoWithAIAction({
        rawText: content,
        pillar,
        sectionLabel: associatedSectionLabel,
        customApiKey: customApiKey.trim() || undefined,
      });

      if (result.error) {
        toast({
          title: "Erreur IA",
          description: result.error,
          variant: "destructive",
        });
        return;
      }

      if (result.summaryTitle) {
        setTitle(result.summaryTitle);
        setAutoGeneratedTitle(result.summaryTitle);
        setIsManualTitleOpen(true);
      }

      if (result.organizedText) {
        setContent(result.organizedText);
      }

      if (result.suggestedChecklist && result.suggestedChecklist.length > 0) {
        const newItems = result.suggestedChecklist.map((item) => ({
          id: `chk-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
          text: item,
          completed: false,
        }));
        setChecklists((prev) => [...prev, ...newItems]);
      }

      setImprovedSuccess(true);
      toast({
        title: "Mémo professionnalisé ✨",
        description: "Le texte a été organisé avec des points clairs et le titre résume le sujet.",
      });
    } catch (err) {
      console.error(err);
      toast({
        title: "Erreur IA",
        description: "Impossible d'améliorer le mémo pour le moment.",
        variant: "destructive",
      });
    } finally {
      setIsImproving(false);
    }
  };

  const handleRestoreOriginalNotes = () => {
    if (!undoBackup) return;
    setTitle(undoBackup.title);
    setAutoGeneratedTitle(undoBackup.title);
    setContent(undoBackup.content);
    setChecklists(undoBackup.checklists);
    setImprovedSuccess(false);
    setUndoBackup(null);
    toast({
      title: "Notes rétablies",
      description: "Votre texte et votre titre initiaux ont été restaurés.",
    });
  };

  // ─── ASSISTANT CONVERSATIONNEL CHATBOT (STYLE CHATGPT) ────────────────────
  const handleSendChatMessage = async (textToSend?: string) => {
    const prompt = (textToSend ?? chatInput).trim();
    if (!prompt || isChatSending) return;

    const userMsgId = `user-${Date.now()}`;
    const newMsg = { id: userMsgId, role: "user" as const, content: prompt };

    const updatedHistory = [...chatMessages, newMsg];
    setChatMessages(updatedHistory);
    setChatInput("");
    setIsChatSending(true);

    try {
      const historyForAi = updatedHistory.map((m) => ({
        role: m.role,
        content: m.content,
      }));

      const result = await chatWithMemoAIAction({
        userPrompt: prompt,
        history: historyForAi,
        currentMemoText: content,
        currentMemoTitle: title || autoGeneratedTitle,
        pillar,
        sectionLabel: associatedSectionLabel,
        customApiKey: customApiKey.trim() || undefined,
      });

      const assistantMsg = {
        id: `ai-${Date.now()}`,
        role: "assistant" as const,
        content: result.reply,
        framingAnalysis: result.framingAnalysis,
        suggestedTitle: result.suggestedTitle,
        suggestedContent: result.suggestedContent,
        suggestedChecklist: result.suggestedChecklist,
        providerUsed: result.providerUsed,
      };

      setChatMessages((prev) => [...prev, assistantMsg]);

      if (result.suggestedContent) {
        setLastGeneratedDraft({
          title: result.suggestedTitle || title || autoGeneratedTitle,
          content: result.suggestedContent,
          checklist: result.suggestedChecklist || [],
        });
      }
    } catch (err) {
      console.error(err);
      toast({
        title: "Erreur Chatbot",
        description: "Impossible d'obtenir une réponse de l'assistant IA.",
        variant: "destructive",
      });
    } finally {
      setIsChatSending(false);
    }
  };

  const applyDraftToPostit = (draft: { title: string; content: string; checklist: string[] }) => {
    if (draft.title) {
      setTitle(draft.title);
      setAutoGeneratedTitle(draft.title);
      setIsManualTitleOpen(true);
    }
    if (draft.content) {
      setContent(draft.content);
    }
    if (draft.checklist && draft.checklist.length > 0) {
      const newItems = draft.checklist.map((item) => ({
        id: `chk-${Date.now()}-${Math.random().toString(36).substring(2, 5)}`,
        text: item,
        completed: false,
      }));
      setChecklists(newItems);
    }
    setActiveTab("postit");
    setImprovedSuccess(true);
    toast({
      title: "Post-it mis à jour par l'IA ✨",
      description: "Le texte structuré, le titre résumé et les actions ont été appliqués !",
    });
  };

  const handleOpenChatbotFromPostit = () => {
    setActiveTab("chatbot");
    if (content.trim() && chatMessages.length <= 1) {
      setChatInput(content.trim());
    }
  };

  // ─── VALIDATION ET ENREGISTREMENT ───────────────────────────────────────────
  const handleSubmit = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!content.trim()) {
      toast({
        title: "Contenu requis",
        description: "Veuillez rédiger le contenu de votre mémo.",
        variant: "destructive",
      });
      return;
    }

    const finalTitle =
      title.trim() ||
      autoGeneratedTitle.trim() ||
      extractFaithfulTitle(content, pillar, associatedSectionLabel);

    if (isEditing && memoToEdit) {
      await updateMemo(memoToEdit.id, {
        title: finalTitle,
        content: content.trim(),
        pillar,
        scope,
        priority,
        associatedSectionHref,
        associatedSectionLabel,
        checklists,
      });
      toast({
        title: "Mémo mis à jour",
        description: `Le mémo "${finalTitle}" a été modifié avec succès.`,
      });
    } else {
      await addMemo({
        title: finalTitle,
        content: content.trim(),
        pillar,
        scope,
        priority,
        associatedSectionHref,
        associatedSectionLabel,
        checklists,
        authorId: user?.id || "user-1",
        authorName: user?.name || "Collaborateur",
        authorRole: user?.role || "Compliance Officer",
      });
      toast({
        title: "Mémo créé",
        description: `Le mémo "${finalTitle}" a été épinglé avec succès.`,
      });
    }

    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-2xl md:max-w-3xl lg:max-w-4xl max-h-[85vh] h-[85vh] flex flex-col p-0 overflow-hidden border border-amber-300/80 dark:border-slate-800 rounded-3xl shadow-2xl bg-amber-50/98 dark:bg-slate-900 z-[200]">
        {/* Ruban / Pin en haut au centre */}
        <div className="absolute -top-3 left-1/2 transform -translate-x-1/2 flex items-center justify-center z-20 pointer-events-none">
          <div className="h-7 w-7 rounded-full bg-rose-500 shadow-md border-2 border-white flex items-center justify-center text-white">
            <Pin className="h-4 w-4 fill-current rotate-45" />
          </div>
        </div>

        {/* ─── EN-TÊTE FIXE (SHRINK-0) ─────────────────────────────────────────── */}
        <div className="shrink-0 px-6 py-3.5 border-b border-amber-200/80 dark:border-slate-800 bg-amber-100/70 dark:bg-slate-900/90 flex justify-between items-center gap-3">
          <div className="flex items-center gap-2.5 min-w-0">
            <Pin className="h-4 w-4 fill-current text-rose-500 rotate-12 shrink-0" />
            <h3 className="text-sm sm:text-base font-black uppercase tracking-tight text-slate-900 dark:text-white truncate">
              {isEditing ? "Modifier le Post-it" : "Nouveau Mémo Post-it"}
            </h3>
          </div>

          {/* Onglets de navigation : Mode Post-it vs Chatbot IA */}
          <div className="flex items-center gap-1.5 p-1 bg-white/80 dark:bg-slate-800/80 rounded-xl border border-amber-200/60 dark:border-slate-700 shadow-xs">
            <button
              type="button"
              onClick={() => setActiveTab("postit")}
              className={cn(
                "px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5",
                activeTab === "postit"
                  ? "bg-amber-500 text-white shadow-xs"
                  : "text-slate-600 dark:text-slate-300 hover:text-slate-900"
              )}
            >
              <FileText className="h-3.5 w-3.5" />
              <span>Note Post-it</span>
            </button>
            <button
              type="button"
              onClick={() => setActiveTab("chatbot")}
              className={cn(
                "px-3 py-1.5 rounded-lg text-xs font-bold transition-all flex items-center gap-1.5",
                activeTab === "chatbot"
                  ? "bg-indigo-600 text-white shadow-xs"
                  : "text-slate-600 dark:text-slate-300 hover:text-indigo-600"
              )}
            >
              <Bot className="h-3.5 w-3.5" />
              <span>Chatbot IA (ChatGPT)</span>
              <Badge className="bg-rose-500 text-white text-[8px] font-black px-1.5 py-0 border-none uppercase ml-0.5">
                Copilot
              </Badge>
            </button>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <button
              type="button"
              onClick={() => setShowKeyConfig(!showKeyConfig)}
              className="p-1.5 rounded-lg text-slate-400 hover:text-amber-600 dark:hover:text-amber-400 text-xs border border-amber-200/50 dark:border-slate-800 bg-white/60 dark:bg-slate-800/60 transition-colors"
              title="Configuration clé API IA (Optionnelle)"
            >
              <KeyRound className="h-3.5 w-3.5" />
            </button>
            <button
              type="button"
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 text-xs transition-colors"
              title="Fermer"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Configuration Clé API Optionnelle (dépliable au sommet) */}
        {showKeyConfig && (
          <div className="shrink-0 p-3 bg-white/95 dark:bg-slate-800/95 border-b border-amber-300/70 dark:border-slate-700 space-y-2 text-xs shadow-sm">
            <div className="flex justify-between items-center">
              <span className="font-bold text-slate-800 dark:text-slate-200 flex items-center gap-1.5">
                <KeyRound className="h-3.5 w-3.5 text-amber-500" /> Clé API IA Personnelle (Groq, Gemini, OpenAI)
              </span>
              <button
                type="button"
                onClick={() => setShowKeyConfig(false)}
                className="text-slate-400 hover:text-slate-600"
              >
                ✕
              </button>
            </div>
            <p className="text-[11px] text-slate-500 dark:text-slate-400">
              Optionnel : Vous pouvez renseigner votre clé personnelle Groq (<code className="font-mono text-indigo-600">gsk_...</code>), Gemini (<code className="font-mono text-indigo-600">AIza...</code>) ou OpenAI (<code className="font-mono text-indigo-600">sk-...</code>). Sans clé, le moteur autonome GRC assure 100% du service.
            </p>
            <div className="flex gap-2">
              <Input
                value={customApiKey}
                onChange={(e) => setCustomApiKey(e.target.value)}
                placeholder="Ex: gsk_... ou AIza... ou sk-..."
                className="text-xs h-8 rounded-xl font-mono"
              />
              <Button
                type="button"
                size="sm"
                onClick={() => handleSaveApiKey(customApiKey)}
                className="h-8 px-3 rounded-xl bg-amber-500 hover:bg-amber-600 text-white text-xs font-bold shrink-0"
              >
                Enregistrer
              </Button>
            </div>
          </div>
        )}

        {/* ─── CORPS DÉFILABLE (FLEX-1 OVERFLOW-Y-AUTO) ─────────────────────────── */}
        <div className="flex-1 overflow-y-auto min-h-0 px-6 py-4 space-y-4">
          {activeTab === "postit" ? (
            /* ══════════════════════════════════════════════════════════════════════
               MODE POST-IT : FORMULAIRE CLASSIQUE AMÉLIORÉ
               ══════════════════════════════════════════════════════════════════════ */
            <div className="space-y-4">
              {/* Champ Titre du Mémo (Résumé synthétique du sujet) */}
              {!isManualTitleOpen && !isEditing ? (
                <div className="p-3 rounded-2xl bg-amber-500/10 dark:bg-slate-800/80 border border-amber-300/60 dark:border-amber-700/50 flex items-center justify-between gap-3 shadow-xs">
                  <div className="flex items-center gap-2.5 min-w-0 flex-1">
                    <div className="p-1.5 rounded-xl bg-amber-500 text-white shrink-0 shadow-sm">
                      {isGeneratingTitle ? (
                        <Loader2 className="h-3.5 w-3.5 animate-spin text-white" />
                      ) : (
                        <Sparkles className="h-3.5 w-3.5" />
                      )}
                    </div>
                    <div className="min-w-0 flex-1">
                      <span className="text-[9.5px] font-black uppercase text-amber-800 dark:text-amber-300 tracking-wider block">
                        Titre du Mémo (Résumé du sujet)
                      </span>
                      <p className="text-xs font-black text-slate-900 dark:text-white truncate">
                        {content.trim()
                          ? title || autoGeneratedTitle || "Génération du titre en cours..."
                          : "Rédigez vos notes pour résumer automatiquement le sujet..."}
                      </p>
                    </div>
                  </div>

                  {content.trim() && (
                    <button
                      type="button"
                      onClick={() => {
                        setTitle(title || autoGeneratedTitle);
                        setIsManualTitleOpen(true);
                      }}
                      className="p-1.5 rounded-lg text-amber-700 dark:text-amber-400 hover:bg-amber-500/20 text-[10px] font-bold shrink-0 flex items-center gap-1 transition-colors"
                      title="Personnaliser le titre manuellement"
                    >
                      <Edit3 className="h-3 w-3" />
                      <span className="hidden sm:inline">Éditer</span>
                    </button>
                  )}
                </div>
              ) : (
                <div className="space-y-1">
                  <div className="flex justify-between items-center">
                    <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                      Titre du Mémo (Résumé du sujet)
                    </label>
                    <button
                      type="button"
                      onClick={() => {
                        const faithful = extractFaithfulTitle(content, pillar, associatedSectionLabel);
                        setTitle(faithful);
                      }}
                      className="text-[9.5px] font-bold text-amber-700 dark:text-amber-400 hover:underline flex items-center gap-1"
                      title="Régénérer le titre résumé du sujet"
                    >
                      <Wand2 className="h-2.5 w-2.5" /> Régénérer résumé
                    </button>
                  </div>
                  <Input
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    placeholder="Titre résumé du sujet..."
                    className="text-sm font-black tracking-tight rounded-xl bg-white/90 dark:bg-slate-800/90 border-amber-200 dark:border-slate-700 text-slate-900 dark:text-white shadow-xs focus-visible:ring-1 focus-visible:ring-amber-500"
                  />
                </div>
              )}

              {/* Volet, Portée, Priorité & Section */}
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
                <div className="space-y-1">
                  <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                    Volet Métier
                  </label>
                  <select
                    value={pillar}
                    onChange={(e) => setPillar(e.target.value as MemoPillar)}
                    className="w-full text-xs font-bold rounded-xl p-2 bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 outline-none shadow-xs"
                  >
                    <option value="LAB_FT">🛡️ LAB / FT</option>
                    <option value="CONFORMITE_REGLEMENTAIRE">⚖️ Conformité Réglementaire</option>
                    <option value="GENERAL">📌 Général</option>
                  </select>
                </div>

                <div className="space-y-1">
                  <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                    Portée / Visibilité
                  </label>
                  <div className="grid grid-cols-2 gap-1 p-1 rounded-xl bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 shadow-xs">
                    <button
                      type="button"
                      onClick={() => setScope("COLLABORATIVE")}
                      className={cn(
                        "py-1 px-1.5 text-[10px] font-bold rounded-lg transition-all flex items-center justify-center gap-1",
                        scope === "COLLABORATIVE"
                          ? "bg-indigo-600 text-white shadow-sm"
                          : "text-slate-500 hover:text-slate-900 dark:hover:text-white"
                      )}
                    >
                      <Users className="h-3 w-3" />
                      Équipe
                    </button>
                    <button
                      type="button"
                      onClick={() => setScope("PRIVATE")}
                      className={cn(
                        "py-1 px-1.5 text-[10px] font-bold rounded-lg transition-all flex items-center justify-center gap-1",
                        scope === "PRIVATE"
                          ? "bg-slate-800 dark:bg-slate-700 text-white shadow-sm"
                          : "text-slate-500 hover:text-slate-900 dark:hover:text-white"
                      )}
                    >
                      <User className="h-3 w-3" />
                      Privé
                    </button>
                  </div>
                </div>

                <div className="space-y-1">
                  <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider">
                    Niveau de Priorité
                  </label>
                  <select
                    value={priority}
                    onChange={(e) => setPriority(e.target.value as MemoPriority)}
                    className="w-full text-xs font-bold rounded-xl p-2 bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 outline-none shadow-xs"
                  >
                    <option value="URGENT">🚨 Urgent / Bloquant</option>
                    <option value="ATTENTION">⚡ Attention</option>
                    <option value="INFO">🟢 Information</option>
                  </select>
                </div>
              </div>

              {/* Section Applicative Associée */}
              <div className="space-y-1">
                <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider flex items-center gap-1">
                  <Layers className="h-3 w-3 text-indigo-500" />
                  Section Applicative Associée
                </label>
                <select
                  value={associatedSectionHref}
                  onChange={(e) => handleSectionChange(e.target.value)}
                  className="w-full text-xs font-semibold rounded-xl p-2 bg-white/90 dark:bg-slate-800/90 border border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 outline-none shadow-xs truncate"
                >
                  {APP_SECTIONS.map((sec) => (
                    <option key={sec.href} value={sec.href}>
                      [{sec.group}] — {sec.label}
                    </option>
                  ))}
                </select>
              </div>

              {/* Zone de texte & Boutons IA */}
              <div className="space-y-2">
                <div className="flex justify-between items-center flex-wrap gap-2">
                  <label className="text-xs sm:text-sm font-black text-slate-800 dark:text-slate-200 uppercase tracking-wider">
                    Contenu du mémo <span className="text-rose-500">*</span>
                  </label>

                  <div className="flex items-center gap-2">
                    {/* Bouton pour basculer vers le Chatbot IA conversationnel */}
                    <button
                      type="button"
                      onClick={handleOpenChatbotFromPostit}
                      className="h-8 px-2.5 rounded-xl bg-white/90 dark:bg-slate-800 border border-indigo-200 dark:border-indigo-800 text-indigo-600 dark:text-indigo-400 hover:bg-indigo-50 dark:hover:bg-slate-700 text-xs font-bold flex items-center gap-1.5 transition-colors shadow-xs"
                      title="Ouvrir le chatbot conversationnel pour dialoguer et affiner vos besoins"
                    >
                      <Bot className="h-3.5 w-3.5" />
                      <span>Chatbot IA (ChatGPT)</span>
                    </button>

                    {/* Bouton d'amélioration directe 1-clic */}
                    <Button
                      type="button"
                      disabled={isImproving || !content.trim()}
                      onClick={handleImproveWithAI}
                      className="h-8 px-3.5 rounded-xl bg-gradient-to-r from-amber-500 via-amber-600 to-indigo-600 hover:from-amber-600 hover:to-indigo-700 text-white text-xs font-black gap-1.5 shadow-md shadow-amber-500/20 transition-all disabled:opacity-40"
                      title="Améliore vos notes brutes : organise le texte avec des points clairs et résume le sujet dans le titre"
                    >
                      {isImproving ? (
                        <>
                          <Loader2 className="h-3.5 w-3.5 animate-spin" />
                          <span>Organisation en cours...</span>
                        </>
                      ) : (
                        <>
                          <Sparkles className="h-3.5 w-3.5 text-amber-200 animate-pulse" />
                          <span>Améliorer avec l'IA ✨</span>
                        </>
                      )}
                    </Button>
                  </div>
                </div>

                {/* Bannière de confirmation / possibilité de rétablir les notes initiales */}
                {improvedSuccess && undoBackup && (
                  <div className="p-2.5 rounded-xl bg-gradient-to-r from-emerald-500/15 via-amber-500/10 to-transparent border border-emerald-300 dark:border-emerald-800 flex items-center justify-between gap-2 text-xs animate-in fade-in duration-200">
                    <span className="font-bold text-emerald-800 dark:text-emerald-300 flex items-center gap-1.5">
                      <Check className="h-3.5 w-3.5 text-emerald-600" />
                      Mémo organisé avec des points clairs & titre résumé du sujet généré !
                    </span>
                    <button
                      type="button"
                      onClick={handleRestoreOriginalNotes}
                      className="text-[11px] font-black text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white flex items-center gap-1 underline transition-colors"
                    >
                      <RotateCcw className="h-3 w-3" /> Rétablir mes notes
                    </button>
                  </div>
                )}

                <Textarea
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                  placeholder="Écrivez vos notes brutes, observations ou points ici... Vous pouvez ensuite cliquer sur 'Améliorer avec l'IA ✨' ou dialoguer avec le 'Chatbot IA (ChatGPT)' pour organiser le texte de façon professionnelle avec des points et générer le titre résumé."
                  rows={7}
                  className="text-sm sm:text-base rounded-2xl font-medium leading-relaxed bg-white/95 dark:bg-slate-800/95 border-amber-200 dark:border-slate-700 text-slate-800 dark:text-slate-200 shadow-xs resize-y focus-visible:ring-1 focus-visible:ring-amber-500 p-3.5"
                  required
                />
              </div>

              {/* Checklist / Actions */}
              <div className="space-y-2 pt-1 border-t border-amber-200/60 dark:border-slate-800">
                <label className="text-[10px] font-black text-slate-500 uppercase tracking-wider flex items-center gap-1">
                  <CheckCircle2 className="h-3 w-3 text-emerald-500" />
                  Checklist / Actions à vérifier
                </label>

                <div className="flex gap-2">
                  <Input
                    value={checklistInput}
                    onChange={(e) => setChecklistInput(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") {
                        e.preventDefault();
                        handleAddChecklistItem();
                      }
                    }}
                    placeholder="Ajouter une action (ex: Contrôler la pièce d'identité)..."
                    className="text-xs rounded-xl h-8 bg-white/90 dark:bg-slate-800/90 border-amber-200 dark:border-slate-700"
                  />
                  <Button
                    type="button"
                    size="sm"
                    onClick={handleAddChecklistItem}
                    className="h-8 px-3 rounded-xl bg-amber-500/20 hover:bg-amber-500/30 text-amber-800 dark:text-amber-200 text-xs font-bold shrink-0"
                  >
                    <Plus className="h-3.5 w-3.5 mr-1" />
                    Ajouter
                  </Button>
                </div>

                {checklists.length > 0 && (
                  <div className="space-y-1 max-h-28 overflow-y-auto pr-1">
                    {checklists.map((chk) => (
                      <div
                        key={chk.id}
                        className="flex items-center justify-between gap-2 px-2.5 py-1.5 bg-white/80 dark:bg-slate-800/80 rounded-xl border border-amber-200/40 dark:border-slate-700 text-xs"
                      >
                        <span className="truncate font-medium text-slate-700 dark:text-slate-300">
                          • {chk.text}
                        </span>
                        <button
                          type="button"
                          onClick={() => handleRemoveChecklistItem(chk.id)}
                          className="text-slate-400 hover:text-rose-500 p-1"
                        >
                          <Trash2 className="h-3 w-3" />
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          ) : (
            /* ══════════════════════════════════════════════════════════════════════
               MODE CHATBOT IA CONVERSATIONNEL (STYLE CHATGPT)
               ══════════════════════════════════════════════════════════════════════ */
            <div className="flex flex-col h-full space-y-3">
              {/* Bannière de cadrage conversationnel */}
              <div className="p-3 rounded-2xl bg-gradient-to-r from-indigo-500/10 via-purple-500/10 to-amber-500/10 border border-indigo-200 dark:border-indigo-900 flex items-start gap-3 shadow-xs">
                <div className="p-2 rounded-xl bg-indigo-600 text-white shrink-0 shadow-sm mt-0.5">
                  <Bot className="h-4 w-4" />
                </div>
                <div className="min-w-0 flex-1">
                  <h4 className="text-xs font-black uppercase text-indigo-950 dark:text-indigo-200 tracking-tight">
                    Assistant IA Conversationnel Copilot GRC
                  </h4>
                  <p className="text-[11px] text-slate-600 dark:text-slate-300 mt-0.5 leading-relaxed">
                    Discutez librement en langage naturel de votre constat ou situation opérationnelle. L'IA cadre votre besoin, structure les points clés de conformité et vous permet d'insérer le résultat dans votre Post-it en 1 clic.
                  </p>
                </div>
              </div>

              {/* Suggestions rapides de prompts */}
              <div className="flex items-center gap-1.5 flex-wrap">
                <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider">
                  Suggestions :
                </span>
                {[
                  "Calcul de risque non adapté après correction de décision",
                  "Seuil espèces > 5 000 DT sans justification d'origine",
                  "Dossier KYC incomplet pour société (RNE manquant)",
                ].map((sug, idx) => (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => handleSendChatMessage(sug)}
                    className="text-[10.5px] font-semibold px-2.5 py-1 rounded-lg bg-white/90 dark:bg-slate-800 border border-amber-200/80 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-amber-100 hover:text-amber-900 transition-colors shadow-2xs"
                  >
                    💬 {sug}
                  </button>
                ))}
              </div>

              {/* Zone des messages de chat */}
              <div className="flex-1 overflow-y-auto space-y-3 p-3 bg-white/60 dark:bg-slate-900/60 rounded-2xl border border-amber-200/50 dark:border-slate-800 min-h-[260px] max-h-[380px]">
                {chatMessages.map((msg) => (
                  <div
                    key={msg.id}
                    className={cn(
                      "flex flex-col space-y-1.5 animate-in fade-in duration-200",
                      msg.role === "user" ? "items-end" : "items-start"
                    )}
                  >
                    <div className="flex items-center gap-1.5 text-[10px] font-black uppercase tracking-wider text-slate-400">
                      {msg.role === "user" ? (
                        <>
                          <span>Vous</span>
                          <User className="h-3 w-3 text-indigo-500" />
                        </>
                      ) : (
                        <>
                          <Bot className="h-3 w-3 text-indigo-600" />
                          <span>Copilot IA</span>
                          {msg.providerUsed && (
                            <Badge variant="outline" className="text-[8px] py-0 px-1 border-indigo-200 text-indigo-600">
                              {msg.providerUsed}
                            </Badge>
                          )}
                        </>
                      )}
                    </div>

                    <div
                      className={cn(
                        "rounded-2xl p-3.5 text-xs sm:text-sm max-w-[92%] leading-relaxed shadow-xs",
                        msg.role === "user"
                          ? "bg-gradient-to-r from-indigo-600 to-indigo-700 text-white rounded-tr-xs"
                          : "bg-white dark:bg-slate-800 text-slate-800 dark:text-slate-200 border border-amber-200/70 dark:border-slate-700 rounded-tl-xs space-y-3"
                      )}
                    >
                      {/* Message texte normal */}
                      <p className="whitespace-pre-line">{msg.content}</p>

                      {/* Si l'assistant a proposé une analyse de cadrage */}
                      {msg.framingAnalysis && (
                        <div className="p-2.5 rounded-xl bg-amber-500/10 dark:bg-amber-950/30 border border-amber-200/80 dark:border-amber-800 text-xs text-amber-950 dark:text-amber-200 whitespace-pre-line leading-relaxed">
                          {msg.framingAnalysis}
                        </div>
                      )}

                      {/* Si l'assistant a généré un mémo structuré */}
                      {msg.suggestedContent && (
                        <div className="p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 space-y-2 text-xs">
                          <div className="flex items-center justify-between gap-2 border-b border-slate-200 dark:border-slate-800 pb-1.5">
                            <span className="font-black text-slate-900 dark:text-white uppercase tracking-tight flex items-center gap-1">
                              <ShieldCheck className="h-3.5 w-3.5 text-emerald-600" />
                              {msg.suggestedTitle || "Note de Conformité"}
                            </span>
                            <Badge className="bg-emerald-600 text-white text-[9px] font-black uppercase">
                              Structuré
                            </Badge>
                          </div>

                          <div className="text-slate-700 dark:text-slate-300 whitespace-pre-line font-medium leading-relaxed">
                            {msg.suggestedContent}
                          </div>

                          {msg.suggestedChecklist && msg.suggestedChecklist.length > 0 && (
                            <div className="pt-2 border-t border-slate-200 dark:border-slate-800 space-y-1">
                              <span className="font-bold text-[10px] uppercase text-slate-500 tracking-wider">
                                Actions recommandées :
                              </span>
                              {msg.suggestedChecklist.map((item, i) => (
                                <div key={i} className="text-[11px] text-slate-600 dark:text-slate-400 flex items-center gap-1.5">
                                  <Check className="h-3 w-3 text-emerald-500 shrink-0" />
                                  <span>{item}</span>
                                </div>
                              ))}
                            </div>
                          )}

                          {/* Bouton pour appliquer directement ce résultat au Post-it */}
                          <div className="pt-2 flex justify-end">
                            <Button
                              type="button"
                              size="sm"
                              onClick={() =>
                                applyDraftToPostit({
                                  title: msg.suggestedTitle || "Note de Conformité",
                                  content: msg.suggestedContent!,
                                  checklist: msg.suggestedChecklist || [],
                                })
                              }
                              className="h-7 px-3 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-black gap-1 shadow-xs"
                            >
                              <ArrowRight className="h-3.5 w-3.5" />
                              Insérer dans le Post-it
                            </Button>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                ))}

                {isChatSending && (
                  <div className="flex items-center gap-2 p-3 bg-white dark:bg-slate-800 rounded-2xl border border-amber-200 dark:border-slate-700 w-fit text-xs text-slate-600">
                    <Loader2 className="h-4 w-4 animate-spin text-indigo-600" />
                    <span>L'IA analyse votre situation et rédige la note...</span>
                  </div>
                )}
                <div ref={chatBottomRef} />
              </div>

              {/* Saisie de message pour le chatbot */}
              <div className="flex gap-2 items-end pt-1">
                <Textarea
                  value={chatInput}
                  onChange={(e) => setChatInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && !e.shiftKey) {
                      e.preventDefault();
                      handleSendChatMessage();
                    }
                  }}
                  placeholder="Posez votre question, décrivez une situation ou demandez un cadrage (ex: que faire si le calcul de risque ne s'adapte pas ?)..."
                  rows={2}
                  className="text-xs sm:text-sm rounded-xl resize-none bg-white/95 dark:bg-slate-800/95 border-amber-200 dark:border-slate-700 text-slate-900 dark:text-white"
                />
                <Button
                  type="button"
                  disabled={!chatInput.trim() || isChatSending}
                  onClick={() => handleSendChatMessage()}
                  className="h-10 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold shrink-0 gap-1.5 shadow-sm disabled:opacity-40"
                >
                  <Send className="h-3.5 w-3.5" />
                  <span>Envoyer</span>
                </Button>
              </div>
            </div>
          )}
        </div>

        {/* ─── PIED DE PAGE FIXE ET TOUJOURS VISIBLE (SHRINK-0) ─────────────────── */}
        <div className="shrink-0 px-6 py-3.5 border-t border-amber-200/80 dark:border-slate-800 bg-amber-100/90 dark:bg-slate-900/95 flex justify-between items-center gap-2 shadow-md z-10">
          <div className="flex items-center gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={onClose}
              className="h-9 px-4 rounded-xl text-xs font-semibold bg-white/90 dark:bg-slate-800 border-amber-200 dark:border-slate-700 hover:bg-white text-slate-700 dark:text-slate-300"
            >
              Annuler
            </Button>
            {activeTab === "chatbot" && (
              <Button
                type="button"
                variant="ghost"
                onClick={() => setActiveTab("postit")}
                className="h-9 px-3 rounded-xl text-xs font-bold text-amber-800 dark:text-amber-300 hover:bg-amber-200/50"
              >
                ← Voir le Post-it
              </Button>
            )}
          </div>

          <div className="flex items-center gap-2">
            {activeTab === "chatbot" && lastGeneratedDraft && (
              <Button
                type="button"
                onClick={() => applyDraftToPostit(lastGeneratedDraft)}
                className="h-9 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold shadow-sm"
              >
                🚀 Appliquer au Post-it
              </Button>
            )}
            {activeTab === "postit" && (
              <Button
                type="button"
                onClick={() => handleSubmit()}
                className="h-9 px-5 rounded-xl bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-white text-xs font-black shadow-md shadow-amber-500/20"
              >
                {isEditing ? "Enregistrer les modifications" : "Épingler le Post-it 📌"}
              </Button>
            )}
          </div>
        </div>

        {/* Effet d'ombre de coin replié en bas à droite */}
        <div
          className="absolute bottom-0 right-0 w-6 h-6 pointer-events-none rounded-br-3xl opacity-30"
          style={{
            background: "linear-gradient(135deg, transparent 50%, rgba(0,0,0,0.15) 50%)",
          }}
        />
      </DialogContent>
    </Dialog>
  );
};
