// ─── Regulatory Watch Types & Initial Dataset (MAE Assurances 2026 - Realigned) ───

export type ComplianceState =
  | 'Conforme'
  | 'Partiellement conforme'
  | 'Non conforme'
  | 'Non applicable'
  | 'En cours de mise en conformité'
  | 'À déterminer';

export type ApplicabilityState = 'Oui' | 'Non' | 'À déterminer' | 'Selon activités';

export type ActionStatus =
  | 'Non démarrée'
  | 'En cours'
  | 'Réalisée'
  | 'En retard'
  | 'Abandonnée';

export interface RegulatoryWatchItem {
  id: number;
  domaine: string;
  sousDomaine: string;
  typeTexte: string;
  referenceTexte: string;
  dateTexte: string;
  autorite: string;
  objet: string;
  articlesCles: string;
  processus: string;
  obligation: string;
  responsable: string;
  controleConformite: string;
  frequence: string;
  preuve: string;
  etatConformite: ComplianceState;
  applicabilite?: ApplicabilityState;
  ecartConstat?: string;
  actionCorrective?: string;
  responsableAction?: string;
  echeance?: string;
  statutAction?: ActionStatus;
  source?: string;
  observations?: string;
}

export interface RegulatorySourceItem {
  source: string;
  url: string;
  perimetre: string;
  regleGestion: string;
}

export const REGULATORY_SOURCES_DATA: RegulatorySourceItem[] = [
  {
    source: 'CGA',
    url: 'https://www.cga.gov.tn/index.php?L=0&id=28',
    perimetre: 'Code des assurances, autres textes, lignes directrices',
    regleGestion: 'Une seule ligne par texte; les avenants sont rattachés au texte initial ou enregistrés comme modification distincte selon leur portée.',
  },
  {
    source: 'CGA – LBA/FT/P',
    url: 'https://www.cga.gov.tn/index.php?L=0&id=222',
    perimetre: 'LBA/FT/P, KYC, cartographie, gel des avoirs',
    regleGestion: 'Les lignes directrices sont enregistrées séparément des lois/règlements.',
  },
  {
    source: 'CGA – Règlements/Décisions',
    url: 'https://www.cga.gov.tn/index.php?L=0&id=33',
    perimetre: 'Règlements et décisions',
    regleGestion: 'Ne pas dupliquer un règlement parce qu\'il apparaît sur plusieurs pages du site.',
  },
  {
    source: 'FTUSA',
    url: 'https://www.ftusanet.org/cadre-institutionnel/code-des-assurances/',
    perimetre: 'Code des assurances et corpus sectoriel',
    regleGestion: 'Utiliser FTUSA comme source complémentaire; privilégier CGA/JORT pour la validation juridique.',
  },
  {
    source: 'RNE',
    url: 'https://www.registre-entreprises.tn/',
    perimetre: 'RNE / bénéficiaire effectif',
    regleGestion: 'Distinguer le texte portant création du RNE des textes spécifiques au bénéficiaire effectif et des textes d\'application.',
  },
];

export const REFERENCE_LISTS = {
  etatsConformite: [
    'Conforme',
    'Partiellement conforme',
    'Non conforme',
    'Non applicable',
    'En cours de mise en conformité',
  ],
  applicabilite: ['Oui', 'Non', 'À déterminer', 'Selon activités'],
  statutAction: ['Non démarrée', 'En cours', 'Réalisée', 'En retard', 'Abandonnée'],
  frequence: [
    'Mensuelle',
    'Trimestrielle',
    'Semestrielle',
    'Annuelle',
    'À chaque nomination',
    'À chaque nouveau contrat',
    'À chaque produit / modification',
    'Événementielle',
    'Continu / événementiel',
    'Selon calendrier CGA',
    'À déterminer',
  ],
};

export const INITIAL_REGULATORY_WATCH_DATA: RegulatoryWatchItem[] = [
  {
    id: 1,
    domaine: 'Assurance Vie / Capitalisation',
    sousDomaine: 'Provisions techniques',
    typeTexte: 'Arrêté',
    referenceTexte: 'Arrêté du ministre des finances du 27 février 2001 fixant la liste, le mode de calcul des provisions techniques et les conditions de leur représentation des sociétés d’assurance',
    dateTexte: '2001-02-27',
    autorite: 'Ministère des Finances',
    objet: 'Provisions techniques et représentation des engagements',
    articlesCles: 'Calcul, constitution et représentation des provisions techniques',
    processus: 'Gestion financière / Actuariat / Vie',
    obligation: 'Vérifier le calcul et la représentation des provisions conformément aux prescriptions',
    responsable: 'Finance / Actuariat / Conformité',
    controleConformite: 'Contrôle de la constitution et de la représentation des provisions conformément aux barèmes',
    frequence: 'Mensuelle / trimestrielle / annuelle selon obligation',
    preuve: 'États prudentiels, calculs actuariels, justificatifs d’actifs',
    etatConformite: 'À déterminer',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Non démarrée',
    source: 'CGA / FTUSA',
    observations: 'Le texte est cité par le règlement CGA n°04/2018 et a été modifié notamment en 2005 et 2009.',
  },
  {
    id: 2,
    domaine: 'Assurance Vie / Capitalisation',
    sousDomaine: 'Contrats',
    typeTexte: 'Arrêté',
    referenceTexte: 'Arrêté du ministre des finances du 22 novembre 2001 fixant le modèle-type des conditions générales des contrats d’assurance',
    dateTexte: '2001-11-22',
    autorite: 'Ministère des Finances',
    objet: 'Modèle-type des conditions générales des contrats d’assurance',
    articlesCles: 'Mentions obligatoires des contrats et conditions générales',
    processus: 'Conception / modification des contrats',
    obligation: 'Contrôler les conditions générales et mentions obligatoires avant mise en commercialisation',
    responsable: 'Juridique / Produits / Conformité',
    controleConformite: 'Revue juridique préalable des conditions générales et notices',
    frequence: 'À chaque nouveau produit / modification',
    preuve: 'Conditions générales validées',
    etatConformite: 'À déterminer',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Non démarrée',
    source: 'CGA / FTUSA',
    observations: 'Texte transversal incluant les contrats Vie/Capitalisation.',
  },
  {
    id: 3,
    domaine: 'Assurance Vie / Capitalisation',
    sousDomaine: 'Actuariat',
    typeTexte: 'Décret',
    referenceTexte: 'Décret n°2002-543 du 5 mars 2002 portant fixation des conditions d’exercice de l’activité d’actuaire habilité à certifier les tarifs d’assurance-vie',
    dateTexte: '2002-03-05',
    autorite: 'Présidence du Gouvernement',
    objet: 'Conditions d’exercice de l’activité d’actuaire habilité à certifier les tarifs d’assurance-vie',
    articlesCles: 'Conditions d’habilitation et d’exercice de l’actuaire certificateur',
    processus: 'Tarification Vie / Capitalisation',
    obligation: 'Vérifier que les certifications sont réalisées par un actuaire habilité',
    responsable: 'Actuariat / Direction Assurance des Personnes',
    controleConformite: 'Vérification du certificat d\'habilitation officiel de l\'actuaire',
    frequence: 'À chaque certification',
    preuve: 'Attestation/certification actuarielle',
    etatConformite: 'À déterminer',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Non démarrée',
    source: 'CGA / FTUSA',
    observations: 'Texte cité par le Règlement CGA n°04/2018.',
  },
  {
    id: 4,
    domaine: 'Assurance Vie / Capitalisation',
    sousDomaine: 'Cadre général',
    typeTexte: 'Règlement CGA',
    referenceTexte: 'Règlement CGA n°01/2016 du 13 juillet 2016 relatif à l’assurance-vie et la capitalisation',
    dateTexte: '2016-07-13',
    autorite: 'CGA',
    objet: 'Réglementation des opérations d’assurance-vie et de capitalisation',
    articlesCles: 'Dispositions relatives aux contrats, opérations, droits et obligations des parties, rachat/avances et exigences applicables à la Vie et à la capitalisation',
    processus: 'Gestion des contrats Vie / Capitalisation',
    obligation: 'Vérifier la conformité des contrats, procédures et opérations Vie/Capitalisation au règlement CGA',
    responsable: 'Direction Assurance des Personnes / Conformité / Juridique',
    controleConformite: 'Audit périodique de conformité des processus de gestion et rachat',
    frequence: 'Permanent',
    preuve: 'Contrats, conditions générales, procédures, contrôles',
    etatConformite: 'À déterminer',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Non démarrée',
    source: 'CGA – Règlements/Décisions',
    observations: 'Référence majeure à intégrer. Le CGA la cite expressément comme règlement relatif à l’assurance-vie et à la capitalisation.',
  },
  {
    id: 5,
    domaine: 'Fiscalité',
    sousDomaine: 'Assurance Vie / Capitalisation',
    typeTexte: 'Loi de finances',
    referenceTexte: 'Loi n°2017-66 du 18 décembre 2017 portant loi de finances pour l’année 2018 – dispositions relatives à l’encouragement de l’épargne à moyen et long terme via les contrats d’assurance-vie et de capitalisation',
    dateTexte: '2017-12-18',
    autorite: 'Ministère des Finances',
    objet: 'Avantages fiscaux liés aux contrats d’assurance-vie et de capitalisation',
    articlesCles: 'Dispositions fiscales applicables à l’épargne via assurance-vie et capitalisation',
    processus: 'Produits Vie / Capitalisation / Fiscalité',
    obligation: 'Contrôler l’application correcte des avantages et règles fiscales',
    responsable: 'Finance / Fiscalité / Produits / Conformité',
    controleConformite: 'Contrôle des paramétrages fiscaux et attestations de déduction',
    frequence: 'À chaque opération / veille fiscale',
    preuve: 'Paramétrage fiscal, procédures, contrôles',
    etatConformite: 'À déterminer',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Non démarrée',
    source: 'Ministère des Finances / JORT',
    observations: 'La Note commune n°20/2018 commente notamment l’article 27.',
  },
  {
    id: 6,
    domaine: 'Assurance Vie / Capitalisation',
    sousDomaine: 'Notes techniques',
    typeTexte: 'Règlement CGA',
    referenceTexte: 'Règlement CGA n°04/2018 du 17 octobre 2018 fixant les spécifications obligatoires à insérer au niveau des notes techniques relatives aux contrats d’assurance Vie et de Capitalisation',
    dateTexte: '2018-10-17',
    autorite: 'CGA',
    objet: 'Spécifications obligatoires des notes techniques Vie et Capitalisation',
    articlesCles: 'Contenu, établissement et certification des notes techniques tarifaires',
    processus: 'Tarification / Produits Vie et Capitalisation',
    obligation: 'Vérifier l\'insertion des spécifications obligatoires dans les notes techniques tarifaires',
    responsable: 'Actuariat / Direction Assurance des Personnes / Conformité',
    controleConformite: 'Vérification et certification des notes techniques avant transmission au CGA',
    frequence: 'À chaque nouveau produit / modification tarifaire',
    preuve: 'Note technique certifiée, transmission au CGA',
    etatConformite: 'À déterminer',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Non démarrée',
    source: 'CGA – Règlements/Décisions',
    observations: 'Entrée en vigueur le 1er janvier 2019 selon le texte.',
  },
  {
    id: 7,
    domaine: 'LBA/FT/P',
    sousDomaine: 'Bénéficiaire effectif / RNE',
    typeTexte: 'Loi',
    referenceTexte: 'Loi n°2018-52 du 29 octobre 2018 portant création du Registre National des Entreprises',
    dateTexte: '2018-10-29',
    autorite: 'Présidence du Gouvernement / RNE',
    objet: 'Création et fonctionnement du Registre National des Entreprises',
    articlesCles: 'Obligations relatives à l’immatriculation et aux informations légales des personnes morales',
    processus: 'KYC personnes morales / bénéficiaire effectif',
    obligation: 'Identification et vérification des bénéficiaires effectifs via consultation du RNE',
    responsable: 'Juridique / Conformité / KYC',
    controleConformite: 'Consultation systématique du service RNE et traçabilité des consultations',
    frequence: 'À l’entrée en relation et lors des mises à jour',
    preuve: 'Extrait RNE, justificatifs UBO, traces de consultation',
    etatConformite: 'En cours de mise en conformité',
    applicabilite: 'Oui',
    ecartConstat: 'Intégration du service RNE en cours de finalisation',
    actionCorrective: 'Finaliser l’intégration/consultation du service RNE et la traçabilité',
    responsableAction: 'Conformité / DSI',
    echeance: '2026-09-02',
    statutAction: 'En cours',
    source: 'RNE / JORT',
    observations: 'À consolider avec les textes d’application RNE et le cadre spécifique bénéficiaire effectif.',
  },
  {
    id: 8,
    domaine: 'LBA/FT/P',
    sousDomaine: 'Évaluation des risques BA/FT',
    typeTexte: 'Lignes directrices',
    referenceTexte: 'Lignes directrices CGA du 14 mai 2025 relatives à la méthodologie de l’évaluation des risques de BA/FT au sein des sociétés d’assurance et de réassurance',
    dateTexte: '2025-05-14',
    autorite: 'CGA',
    objet: 'Méthodologie d’évaluation des risques BA/FT',
    articlesCles: 'Méthodologie, facteurs de risque et approche par les risques',
    processus: 'Évaluation des risques LBA/FT/P',
    obligation: 'Élaboration et actualisation périodique de l\'évaluation globale des risques BA/FT',
    responsable: 'Conformité',
    controleConformite: 'Revue et validation annuelle de la cartographie des risques selon la méthodologie CGA',
    frequence: 'Au moins annuelle et lors d’un changement significatif',
    preuve: 'Évaluation des risques, cartographie, PV de revue',
    etatConformite: 'En cours de mise en conformité',
    applicabilite: 'Oui',
    ecartConstat: 'Actualisation méthodologique 2025 en cours d\'alignement',
    actionCorrective: 'Actualiser l’évaluation et la cartographie selon la méthodologie CGA',
    responsableAction: 'Conformité',
    echeance: '2026-09-02',
    statutAction: 'En cours',
    source: 'CGA – LBA/FT/P',
    observations: 'À distinguer de la loi et du règlement CGA n°2/2019.',
  },
  {
    id: 9,
    domaine: 'LBA/FT/P',
    sousDomaine: 'Gel des avoirs / sanctions financières ciblées',
    typeTexte: 'Lignes directrices conjointes',
    referenceTexte: 'Lignes directrices conjointes CGA/CNLCT du 24 juillet 2025 relatives à la mise en œuvre des mesures de gel des avoirs dans le secteur des assurances',
    dateTexte: '2025-07-24',
    autorite: 'CGA / CNLCT',
    objet: 'Mise en œuvre des mesures de gel des avoirs',
    articlesCles: 'Filtrage, gel, déclaration et mesures de prévention relatives aux sanctions financières ciblées',
    processus: 'Sanctions / filtrage / gel des avoirs',
    obligation: 'Filtrage continu des listes de sanctions, gel immédiat sous 8h et déclaration CNLCT',
    responsable: 'Conformité / Métiers / SI',
    controleConformite: 'Tests réguliers du moteur de filtrage et du circuit d\'escalade en cas d\'alerte',
    frequence: 'Continu',
    preuve: 'Résultats de filtrage, alertes, preuves de gel/déclaration',
    etatConformite: 'En cours de mise en conformité',
    applicabilite: 'Oui',
    ecartConstat: 'Dispositif de test opérationnel à formaliser',
    actionCorrective: 'Formaliser et tester le dispositif de gel et de filtrage',
    responsableAction: 'Conformité',
    echeance: '2026-09-02',
    statutAction: 'En cours',
    source: 'CGA / CNLCT',
    observations: 'Ligne directrice sectorielle conjointe; ne pas la dupliquer avec la loi LBA/FT/P.',
  },
  {
    id: 10,
    domaine: 'LBA/FT/P',
    sousDomaine: 'KYC / connaissance de la relation d’affaires',
    typeTexte: 'Lignes directrices',
    referenceTexte: 'Lignes directrices CGA du 19 août 2025 relatives à l’identification, à la vérification de l’identité et à la connaissance des relations d’affaires dans le secteur des assurances',
    dateTexte: '2025-08-19',
    autorite: 'CGA',
    objet: 'Identification, vérification de l’identité et connaissance des relations d’affaires dans le secteur des assurances',
    articlesCles: 'Ensemble des dispositions opérationnelles relatives au KYC',
    processus: 'KYC / entrée en relation / mise à jour',
    obligation: 'Identification et vérification rigoureuses de l\'identité et du profil de risque client',
    responsable: 'Conformité / Réseau / Métiers',
    controleConformite: 'Contrôles de premier et second niveau sur la complétude des dossiers KYC',
    frequence: 'Périodique',
    preuve: 'Fiches KYC, pièces justificatives, rapports de contrôle',
    etatConformite: 'En cours de mise en conformité',
    applicabilite: 'Oui',
    ecartConstat: 'Champs KYC à aligner sur les nouvelles directives 2025',
    actionCorrective: 'Mettre en conformité les champs et contrôles KYC avec les lignes directrices',
    responsableAction: 'Conformité',
    echeance: '2026-09-02',
    statutAction: 'En cours',
    source: 'CGA – LBA/FT/P',
    observations: 'Texte à conserver distinct du règlement CGA n°2/2019 : il constitue une ligne directrice opérationnelle.',
  },
  {
    id: 11,
    domaine: 'LBA/FT/P',
    sousDomaine: 'Bénéficiaire effectif',
    typeTexte: 'Arrêté',
    referenceTexte: 'Arrêté de la Cheffe du Gouvernement du 13 janvier 2026 relatif aux critères de détermination du bénéficiaire effectif',
    dateTexte: '2026-01-13',
    autorite: 'Cheffe du Gouvernement',
    objet: 'Critères de détermination du bénéficiaire effectif',
    articlesCles: 'Détermination et identification du bénéficiaire effectif',
    processus: 'KYC personnes morales / UBO',
    obligation: 'Application des critères 2026 pour identifier les personnes physiques bénéficiaires effectifs',
    responsable: 'Conformité / Juridique / KYC',
    controleConformite: 'Contrôle des organigrammes capitalistiques et seuils de contrôle effectif',
    frequence: 'À l’entrée en relation et lors des changements',
    preuve: 'Fiche UBO, organigramme capitalistique, justificatifs',
    etatConformite: 'En cours de mise en conformité',
    applicabilite: 'Oui',
    ecartConstat: 'Mise à jour des procédures UBO requise suite à l\'arrêté 2026',
    actionCorrective: 'Mettre à jour la procédure UBO et le paramétrage KYC',
    responsableAction: 'Conformité / DSI',
    echeance: '2026-09-02',
    statutAction: 'En cours',
    source: 'JORT / RNE',
    observations: 'À ne pas confondre avec la loi portant création du RNE : deux références distinctes.',
  },
  {
    id: 12,
    domaine: 'LBA/FT/P',
    sousDomaine: 'Cartographie des risques',
    typeTexte: 'Lignes directrices',
    referenceTexte: 'Lignes directrices CGA relatives à l’élaboration d’une cartographie de risques',
    dateTexte: '',
    autorite: 'CGA',
    objet: 'Élaboration d’une cartographie des risques',
    articlesCles: 'Principes et méthodologie d’élaboration de la cartographie',
    processus: 'Cartographie des risques conformité / LBA/FT',
    obligation: 'Structuration et formalisation de la cartographie des risques de non-conformité',
    responsable: 'Conformité / Gestion des risques',
    controleConformite: 'Revue périodique et mise à jour de la grille d\'évaluation des risques',
    frequence: 'Annuelle',
    preuve: 'Cartographie formalisée, grille d\'évaluation, PV de validation',
    etatConformite: 'En cours de mise en conformité',
    applicabilite: 'Oui',
    ecartConstat: 'Harmonisation du format documentaire en cours',
    actionCorrective: 'Formaliser la cartographie conformément aux lignes directrices CGA',
    responsableAction: 'Conformité',
    echeance: '2026-09-02',
    statutAction: 'En cours',
    source: 'CGA – LBA/FT/P',
    observations: 'Date à compléter après vérification du document source CGA.',
  },
  {
    id: 13,
    domaine: 'Cadre sectoriel',
    sousDomaine: 'Modifications du Code',
    typeTexte: 'Loi',
    referenceTexte: 'Loi n°2002-37 du 1er avril 2002',
    dateTexte: '01/04/2002',
    autorite: 'Législateur tunisien',
    objet: 'Modification et complément du Code des assurances',
    articlesCles: 'Dispositions relatives notamment aux entreprises de réassurance et contrôle',
    processus: 'Gouvernance / réassurance',
    obligation: 'Respect des exigences applicables',
    responsable: 'Direction Générale / Juridique',
    controleConformite: 'Veille sur les modifications du Code des assurances',
    frequence: 'Continue',
    preuve: 'Statuts, traités de réassurance',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA',
    observations: 'Modifications intégrées au corpus de base.',
  },
  {
    id: 14,
    domaine: 'Comptabilité',
    sousDomaine: 'Provisions pour créances',
    typeTexte: 'Décision CGA',
    referenceTexte: 'Décision n°01/2021 du 1er décembre 2021',
    dateTexte: '01/12/2021',
    autorite: 'CGA',
    objet: 'Base et méthode de calcul des provisions pour dépréciation des créances sur assurés et intermédiaires',
    articlesCles: 'Méthode de calcul',
    processus: 'Finance / recouvrement',
    obligation: 'Calculer et comptabiliser selon la méthode prescrite',
    responsable: 'Finance / Recouvrement / Comptabilité',
    controleConformite: 'Calcul des dépréciations créances selon les barèmes CGA',
    frequence: 'Clôture / périodique',
    preuve: 'États comptables, écritures d\'inventaire',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'CGA – Règlements/Décisions',
    observations: 'Appliquée lors des clôtures trimestrielles et annuelles.',
  },
  {
    id: 15,
    domaine: 'Gouvernance',
    sousDomaine: 'Nominations',
    typeTexte: 'Règlement CGA',
    referenceTexte: 'Règlement CGA n°02/2018 du 2 avril 2018',
    dateTexte: '02/04/2018',
    autorite: 'CGA',
    objet: 'Information du CGA sur les nominations au sein des structures d\'administration, de gestion et de contrôle',
    articlesCles: 'Obligations de notification préalable',
    processus: 'Nominations / fonctions de contrôle',
    obligation: 'Informer le CGA dans les conditions requises',
    responsable: 'Secrétariat Général / RH / Conformité',
    controleConformite: 'Notification préalable au régulateur pour chaque nomination clé',
    frequence: 'À chaque nomination',
    preuve: 'Courriers de notification CGA, accusés de réception',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'CGA – Règlements/Décisions',
    observations: 'Obligation suivie systématiquement par le secrétariat général.',
  },
  {
    id: 16,
    domaine: 'Cybersécurité',
    sousDomaine: 'Sécurité informatique',
    typeTexte: 'Loi',
    referenceTexte: 'Loi n°2004-5 du 3 février 2004 relative à la sécurité informatique',
    dateTexte: '03/02/2004',
    autorite: 'Législateur tunisien',
    objet: 'Sécurité informatique',
    articlesCles: 'Sécurité des systèmes et obligations associées',
    processus: 'DSI / SI',
    obligation: 'Mettre en œuvre les exigences de sécurité applicables',
    responsable: 'DSI / RSSI',
    controleConformite: 'Audits périodiques de sécurité informatique et respect des normes ANSI/ANCS',
    frequence: 'Annuelle',
    preuve: 'Rapports d\'audit ANCS, PSSI à jour',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'JORT / ANSI',
    observations: 'Audit de sécurité périodique obligatoire.',
  },
  {
    id: 17,
    domaine: 'Gouvernance',
    sousDomaine: 'Sociétés',
    typeTexte: 'Loi',
    referenceTexte: 'Loi n°2000-93 du 3 novembre 2000 portant promulgation du Code des sociétés commerciales',
    dateTexte: '03/11/2000',
    autorite: 'Législateur tunisien',
    objet: 'Code des sociétés commerciales',
    articlesCles: 'Gouvernance, organes, décisions, comptes',
    processus: 'Gouvernance / juridique',
    obligation: 'Respecter les règles sociétaires applicables',
    responsable: 'Juridique / Direction Générale',
    controleConformite: 'Tenue des assemblées, dépôts légaux et gouvernance sociétaire',
    frequence: 'Annuelle',
    preuve: 'PV d\'AG, rapports de gestion, certifications CAC',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'JORT',
    observations: 'Socle légal pour le fonctionnement de la société.',
  },
  {
    id: 18,
    domaine: 'Actuariat',
    sousDomaine: 'Actuaire habilité',
    typeTexte: 'Décret',
    referenceTexte: 'Décret n°2002-543 du 5 mars 2002',
    dateTexte: '05/03/2002',
    autorite: 'Gouvernement',
    objet: 'Conditions d\'exercice de l\'activité d\'actuaire habilité à certifier les tarifs vie',
    articlesCles: 'Conditions d\'habilitation',
    processus: 'Actuariat vie',
    obligation: 'Vérifier recours à un actuaire habilité',
    responsable: 'Actuariat / Direction Assurance des Personnes',
    controleConformite: 'Vérification de l\'habilitation officielle de l\'actuaire certificateur',
    frequence: 'À chaque certification',
    preuve: 'Attestations d\'habilitation',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA / CGA',
    observations: 'Texte d\'application du Code des assurances.',
  },
  {
    id: 19,
    domaine: 'Experts',
    sousDomaine: 'Experts et commissaires d\'avaries',
    typeTexte: 'Décret',
    referenceTexte: 'Décret n°2002-544 du 5 mars 2002',
    dateTexte: '05/03/2002',
    autorite: 'Gouvernement',
    objet: 'Conditions d\'inscription et de radiation des experts et commissaires d\'avaries',
    articlesCles: 'Conditions professionnelles',
    processus: 'Sinistres / expertise',
    obligation: 'Vérifier habilitation des intervenants',
    responsable: 'Direction Sinistres',
    controleConformite: 'Contrôle des inscriptions sur le tableau des experts assermentés',
    frequence: 'Annuelle',
    preuve: 'Liste à jour des experts missionnés',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA / CGA',
    observations: 'Contrôle annuel des prestataires experts.',
  },
  {
    id: 20,
    domaine: 'Reporting',
    sousDomaine: 'Collecte des données',
    typeTexte: 'Règlement CGA',
    referenceTexte: 'Règlement CGA n°02/2025 du 5 juin 2025',
    dateTexte: '05/06/2025',
    autorite: 'CGA',
    objet: 'Plateforme de collecte automatique des données à transmettre au CGA',
    articlesCles: 'Modalités de collecte et transmission',
    processus: 'Reporting / DSI / Finance',
    obligation: 'Assurer la qualité et transmission des données',
    responsable: 'Reporting / DSI / Finance',
    controleConformite: 'Télétransmission automatique des données réglementaires vers la plateforme CGA',
    frequence: 'Selon calendrier CGA',
    preuve: 'Accusés de transmission et journaux de flux',
    etatConformite: 'En cours de mise en conformité',
    applicabilite: 'Oui',
    ecartConstat: 'Paramétrage des connecteurs en cours',
    actionCorrective: 'Finaliser l\'interfaçage avec la plateforme automatique CGA',
    responsableAction: 'DSI / Reporting',
    echeance: '2026-12-31',
    statutAction: 'En cours',
    source: 'CGA – Règlements/Décisions',
    observations: 'Nouveau dispositif de reporting automatisé.',
  },
  {
    id: 21,
    domaine: 'Exportation',
    sousDomaine: 'Financement avant expédition',
    typeTexte: 'Loi / Décret',
    referenceTexte: 'Loi n°99-95 du 6 décembre 1999 et décret n°2000-23 du 3 janvier 2000',
    dateTexte: '06/12/1999 / 03/01/2000',
    autorite: 'Législateur / Gouvernement',
    objet: 'Fonds de garantie de financement des exportations avant expédition',
    articlesCles: 'Garantie et fonctionnement du fonds',
    processus: 'Assurance export / financement',
    obligation: 'Vérifier l\'applicabilité',
    responsable: 'Direction Technique / Finance',
    controleConformite: 'Revue de périmètre des garanties export',
    frequence: 'À déterminer',
    preuve: 'Note d\'analyse d\'applicabilité',
    etatConformite: 'Non applicable',
    applicabilite: 'Non',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA',
    observations: 'Non applicable selon le périmètre d\'activité actuel de la MAE.',
  },
  {
    id: 22,
    domaine: 'Reporting',
    sousDomaine: 'Documents périodiques',
    typeTexte: 'Arrêté',
    referenceTexte: 'Arrêté du ministre des finances du 7 mars 2003',
    dateTexte: '07/03/2003',
    autorite: 'Ministère des Finances',
    objet: 'Liste et forme des documents et états de conjoncture des entreprises d\'assurance et de réassurance',
    articlesCles: 'Documents et états périodiques',
    processus: 'Reporting',
    obligation: 'Produire les états dans les formats requis',
    responsable: 'Direction Financière / Reporting',
    controleConformite: 'Vérification de conformité des états périodiques transmis au CGA',
    frequence: 'Trimestrielle / Annuelle',
    preuve: 'Copies des états périodiques certifiés',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'CGA / FTUSA',
    observations: 'États de conjoncture réguliers.',
  },
  {
    id: 23,
    domaine: 'LBA/FT/P',
    sousDomaine: 'Dispositif national',
    typeTexte: 'Loi organique',
    referenceTexte: 'Loi organique n°2015-26 du 7 août 2015, telle que modifiée et complétée',
    dateTexte: '07/08/2015',
    autorite: 'Législateur tunisien',
    objet: 'Lutte contre le terrorisme et la répression du blanchiment d\'argent',
    articlesCles: 'Dispositions LBA/FT applicables aux assujettis',
    processus: 'LBA/FT/P',
    obligation: 'Respecter les obligations légales et réglementaires',
    responsable: 'Direction Conformité / DG',
    controleConformite: 'Contrôle continu du dispositif de vigilance, filtrage, déclarations et formation',
    frequence: 'Continu',
    preuve: 'Rapports annuels LBA/FT, déclarations CTAF, audits',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'CTAF / JORT',
    observations: 'Texte fondamental régissant l\'ensemble des obligations LBA/FT.',
  },
  {
    id: 24,
    domaine: 'Automobile',
    sousDomaine: 'Frais de soins',
    typeTexte: 'Arrêté',
    referenceTexte: 'Arrêté conjoint du 8 juin 2006',
    dateTexte: '08/06/2006',
    autorite: 'Ministères concernés',
    objet: 'Tarifs cadres des frais de soins des victimes des accidents de la circulation',
    articlesCles: 'Tarifs de prise en charge',
    processus: 'Sinistres corporels',
    obligation: 'Appliquer les tarifs en vigueur',
    responsable: 'Direction Sinistres Auto',
    controleConformite: 'Application des barèmes légaux lors du règlement des sinistres corporels',
    frequence: 'À chaque sinistre',
    preuve: 'Décomptes d\'indemnisation et quittances',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA',
    observations: 'Barème appliqué par les gestionnaires sinistres.',
  },
  {
    id: 25,
    domaine: 'Bancassurance',
    sousDomaine: 'Distribution',
    typeTexte: 'Arrêté',
    referenceTexte: 'Arrêté du ministre des finances du 8 août 2002, modifié le 10 mars 2004',
    dateTexte: '08/08/2002 / 10/03/2004',
    autorite: 'Ministère des Finances',
    objet: 'Catégories d\'assurance pouvant être présentées par les banques et l\'Office national des postes',
    articlesCles: 'Catégories autorisées',
    processus: 'Bancassurance',
    obligation: 'Vérifier le périmètre des produits distribués',
    responsable: 'Direction Commerciale / Juridique',
    controleConformite: 'Revue des conventions de distribution bancaire',
    frequence: 'À chaque convention',
    preuve: 'Conventions de partenariat validées',
    etatConformite: 'Conforme',
    applicabilite: 'Selon activités',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA / BCT',
    observations: 'Encadrement des produits distribués par le réseau bancaire et postal.',
  },
  {
    id: 26,
    domaine: 'Électronique',
    sousDomaine: 'Échanges électroniques',
    typeTexte: 'Loi',
    referenceTexte: 'Loi n°2000-83 du 9 août 2000 relative aux échanges et au commerce électroniques',
    dateTexte: '09/08/2000',
    autorite: 'Législateur tunisien',
    objet: 'Échanges et commerce électroniques',
    articlesCles: 'Validité et sécurité des échanges électroniques',
    processus: 'Digital / contrats / SI',
    obligation: 'Sécuriser et encadrer les échanges électroniques',
    responsable: 'DSI / Juridique',
    controleConformite: 'Certification des plateformes web et signatures électroniques',
    frequence: 'Annuelle',
    preuve: 'Certificats électroniques, conventions de preuve',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'ANCS / JORT',
    observations: 'Cadre légal de la souscription et gestion électronique.',
  },
  {
    id: 27,
    domaine: 'Reporting',
    sousDomaine: 'Rapport annuel',
    typeTexte: 'Règlement CGA',
    referenceTexte: 'Règlement CGA n°01/2021 du 11 février 2022, modifié par avenant du 5 juin 2025',
    dateTexte: '11/02/2022 / 05/06/2025',
    autorite: 'CGA',
    objet: 'Obligations de reporting et éléments constitutifs du rapport annuel',
    articlesCles: 'Reporting et rapport annuel',
    processus: 'Finance / reporting / directions contributrices',
    obligation: 'Respecter contenu, délais et fiabilité des reportings',
    responsable: 'Finance / Reporting / Conformité',
    controleConformite: 'Établissement et transmission du rapport annuel de conformité et contrôle interne',
    frequence: 'Annuelle',
    preuve: 'Rapport annuel transmis au CGA avec récépissé',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'CGA – Règlements/Décisions',
    observations: 'Rapport annuel consolidé déposé dans les délais légaux.',
  },
  {
    id: 28,
    domaine: 'Collectif',
    sousDomaine: 'Contrats collectifs',
    typeTexte: 'Règlement CGA',
    referenceTexte: 'Règlement CGA n°03/2022 du 11 novembre 2022 + avenant',
    dateTexte: '11/11/2022',
    autorite: 'CGA',
    objet: 'Organisation des contrats d\'assurance collectifs, conventions cadres et conventions bilatérales',
    articlesCles: 'Règles de conclusion et gestion',
    processus: 'Contrats collectifs',
    obligation: 'Respecter les exigences contractuelles et d\'information',
    responsable: 'Direction Assurance Collective',
    controleConformite: 'Vérification des clauses obligatoires dans les conventions collectives',
    frequence: 'À chaque nouveau contrat',
    preuve: 'Contrats types et avenants conformes',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'CGA – Règlements/Décisions',
    observations: 'Réglementation relative aux assurances groupe et conventions bilatérales.',
  },
  {
    id: 29,
    domaine: 'Automobile',
    sousDomaine: 'Attestation d\'assurance',
    typeTexte: 'Arrêté',
    referenceTexte: 'Arrêté du ministre des finances du 12 avril 2006',
    dateTexte: '12/04/2006',
    autorite: 'Ministère des Finances',
    objet: 'Forme et contenu de l\'attestation d\'assurance',
    articlesCles: 'Mentions obligatoires et présentation',
    processus: 'Automobile / réseau',
    obligation: 'Délivrer des attestations conformes',
    responsable: 'Production Auto / Réseau',
    controleConformite: 'Contrôle des modèles d\'attestations et certificats verts',
    frequence: 'Continu',
    preuve: 'Spécimens validés',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA / CGA',
    observations: 'Forme officielle des macarons et attestations auto.',
  },
  {
    id: 30,
    domaine: 'Bénéficiaire effectif',
    sousDomaine: 'RNE / BE',
    typeTexte: 'Arrêté',
    referenceTexte: 'Arrêté de la Cheffe du Gouvernement du 13 janvier 2026 relatif à la détermination du bénéficiaire effectif',
    dateTexte: '13/01/2026',
    autorite: 'Gouvernement',
    objet: 'Détermination du bénéficiaire effectif',
    articlesCles: 'Identification du BE',
    processus: 'KYC personnes morales',
    obligation: 'Identifier et vérifier le BE conformément aux règles en vigueur',
    responsable: 'Conformité / KYC',
    controleConformite: 'Mise en œuvre des critères d\'identification des personnes physiques bénéficiaires effectifs',
    frequence: 'À chaque entrée en relation',
    preuve: 'Fiches BE, pièces d\'identité, organigrammes',
    etatConformite: 'En cours de mise en conformité',
    applicabilite: 'Oui',
    ecartConstat: 'Intégration des critères 2026 en cours',
    actionCorrective: 'Adapter la matrice d\'identification UBO aux nouvelles dispositions 2026',
    responsableAction: 'Conformité / DSI',
    echeance: '2026-09-02',
    statutAction: 'En cours',
    source: 'JORT / RNE',
    observations: 'Texte d\'actualisation clé pour le KYC personnes morales.',
  },
  {
    id: 31,
    domaine: 'Fonds sectoriels',
    sousDomaine: 'Fonds de garantie des assurés',
    typeTexte: 'Décret',
    referenceTexte: 'Décret n°2002-418 du 14 février 2002',
    dateTexte: '2002-02-14',
    autorite: 'Gouvernement',
    objet: 'Conditions d\'intervention, fonctionnement et financement du Fonds de garantie des assurés',
    articlesCles: 'Contribution et modalités de fonctionnement',
    processus: 'Finance',
    obligation: 'Calculer et verser la contribution selon règles',
    responsable: 'Direction Financière',
    controleConformite: 'Calcul et versement régulier des quotes-parts au Fonds de garantie',
    frequence: 'Trimestrielle',
    preuve: 'Justificatifs de virement bancaire et états déclaratifs',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA / CGA',
    observations: 'Contribution sectorielle obligatoire.',
  },
  {
    id: 32,
    domaine: 'LBA/FT/P',
    sousDomaine: 'Évaluation des risques',
    typeTexte: 'Lignes directrices CGA',
    referenceTexte: 'Lignes directrices du 14 mai 2025 relatives à la méthodologie d\'évaluation des risques de BA/FT au sein des sociétés d\'assurance et de réassurance',
    dateTexte: '14/05/2025',
    autorite: 'CGA',
    objet: 'Méthodologie d\'évaluation des risques BA/FT',
    articlesCles: 'Approche fondée sur les risques',
    processus: 'Risk assessment LBA/FT',
    obligation: 'Réaliser et actualiser l\'évaluation des risques BA/FT',
    responsable: 'Direction Conformité',
    controleConformite: 'Revue de la cartographie méthodologique selon les critères CGA 2025',
    frequence: 'Annuelle',
    preuve: 'Rapport méthodologique, PV de comité des risques',
    etatConformite: 'En cours de mise en conformité',
    applicabilite: 'Oui',
    ecartConstat: 'Revue méthodologique en cours d\'intégration',
    actionCorrective: 'Intégrer les nouvelles typologies sectorielles dans la cartographie',
    responsableAction: 'Conformité',
    echeance: '2026-09-02',
    statutAction: 'En cours',
    source: 'CGA – LBA/FT/P',
    observations: 'Document d\'orientation opérationnelle du régulateur.',
  },
  {
    id: 33,
    domaine: 'Automobile',
    sousDomaine: 'Bureau central de tarification',
    typeTexte: 'Arrêté',
    referenceTexte: 'Arrêté du ministre des finances du 17 janvier 2006',
    dateTexte: '17/01/2006',
    autorite: 'Ministère des Finances',
    objet: 'Règles de fonctionnement du bureau central de tarification',
    articlesCles: 'Procédure en cas de refus d\'assurance RC automobile',
    processus: 'Automobile',
    obligation: 'Respecter les obligations en cas de saisine du bureau',
    responsable: 'Direction Technique Automobile',
    controleConformite: 'Traitement des décisions du BCT et émission des contrats imposés',
    frequence: 'Événementielle',
    preuve: 'Dossiers BCT et polices correspondantes',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA',
    observations: 'Respect strict des tarifs fixés par le BCT.',
  },
  {
    id: 34,
    domaine: 'Contrats',
    sousDomaine: 'Conditions générales',
    typeTexte: 'Arrêté',
    referenceTexte: 'Arrêté du ministre des finances du 22 novembre 2001',
    dateTexte: '22/11/2001',
    autorite: 'Ministère des Finances',
    objet: 'Modèle-type des conditions générales des contrats d\'assurance',
    articlesCles: 'Mentions obligatoires des contrats',
    processus: 'Produits / juridique / commercial',
    obligation: 'Vérifier conformité des contrats et notices',
    responsable: 'Juridique / Produits',
    controleConformite: 'Revue juridique avant commercialisation de tout nouveau produit',
    frequence: 'À chaque produit / modification',
    preuve: 'Visas juridiques, conditions générales',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA / CGA',
    observations: 'Modèle général applicable à l\'ensemble des branches non-vie et vie.',
  },
  {
    id: 35,
    domaine: 'Automobile',
    sousDomaine: 'Véhicules non immatriculés',
    typeTexte: 'Décret',
    referenceTexte: 'Décret n°2006-873 du 27 mars 2006',
    dateTexte: '27/03/2006',
    autorite: 'Gouvernement',
    objet: 'Conditions d\'application de l\'assurance frontière et justificatifs',
    articlesCles: 'Attestation, assurance frontière',
    processus: 'Automobile',
    obligation: 'Respecter les conditions d\'émission et justificatifs',
    responsable: 'Direction Réseau / Frontières',
    controleConformite: 'Vérification de la validité des polices frontières et quittances',
    frequence: 'Périodique',
    preuve: 'Bordereaux d\'émission des bureaux frontière',
    etatConformite: 'Conforme',
    applicabilite: 'Selon activités',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'FTUSA',
    observations: 'Gestion des contrats d\'assurance frontière.',
  },
  {
    id: 36,
    domaine: 'Protection des données',
    sousDomaine: 'Données personnelles',
    typeTexte: 'Loi organique',
    referenceTexte: 'Loi organique n°2004-63 du 27 juillet 2004',
    dateTexte: '27/07/2004',
    autorite: 'Législateur tunisien',
    objet: 'Protection des données à caractère personnel',
    articlesCles: 'Traitements, droits, formalités, sécurité',
    processus: 'KYC / RH / SI / clients',
    obligation: 'Respecter les obligations applicables aux traitements',
    responsable: 'DPO / Direction Conformité / DSI',
    controleConformite: 'Déclarations auprès de l\'INPDP et sécurisation des données personnelles',
    frequence: 'Annuelle',
    preuve: 'Récépissés INPDP, registre des traitements',
    etatConformite: 'Conforme',
    applicabilite: 'Oui',
    ecartConstat: '',
    actionCorrective: '',
    responsableAction: '',
    echeance: '',
    statutAction: 'Réalisée',
    source: 'INPDP / JORT',
    observations: 'Obligations INPDP suivies par le DPO / Conformité.',
  },
  {
    id: 37,
    domaine: 'Paiements',
    sousDomaine: 'Chèques',
    typeTexte: 'Loi',
    referenceTexte: 'Réforme du régime des chèques – textes législatifs et réglementaires en vigueur',
    dateTexte: 'À vérifier',
    autorite: 'Législateur / BCT',
    objet: 'Réforme du régime des chèques',
    articlesCles: 'Règles applicables aux paiements et encaissements',
    processus: 'Trésorerie / recouvrement / comptabilité',
    obligation: 'Adapter les procédures et contrôles',
    responsable: 'Trésorerie / Recouvrement / Comptabilité',
    controleConformite: 'Mise à niveau des règles d\'acceptation des chèques et interfaçage avec les plateformes BCT',
    frequence: 'Selon calendrier BCT',
    preuve: 'Circulaires internes, procédures d\'encaissement adaptées',
    etatConformite: 'En cours de mise en conformité',
    applicabilite: 'Oui',
    ecartConstat: 'Circulaires BCT d\'application en cours d\'intégration',
    actionCorrective: 'Mettre à jour les procédures d\'encaissement chèques suite aux réformes légales',
    responsableAction: 'Trésorerie / Conformité',
    echeance: '2026-09-02',
    statutAction: 'En cours',
    source: 'BCT / JORT',
    observations: 'Veille active sur les circulaires d\'application de la BCT.',
  },
];
